"""
Translate enjoy-your-life chapters 56-70 (except 059) to Indonesian.
"""
import json
from pathlib import Path

BOOK_DIR = Path('web/data/books/enjoy-your-life')

translations = {}

# ============================================================
# Chapter 056
# ============================================================
translations['056'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Berhati-hatilah dan jangan biarkan lisanmu tergelincir dengan berkata, "Mengapa kamu tidak membeli kursi baru? '
        'Setengah lampu gantungmu tidak berfungsi. Mengapa tidak membeli yang baru? Cat dindingmu sudah mengelupas! '
        'Mengapa tidak dicat ulang?" Saudaraku, ia tidak meminta saranmu. Kamu bukan dekorator profesional yang dimintai '
        'nasihat. Diamlah. Mungkin ia tidak mampu mengubah dekorasi itu. Mungkin ia sedang dalam kesulitan finansial, '
        'dan sebagainya. Tidak ada yang lebih menyusahkan daripada seseorang yang mempermalukan orang lain dengan '
        'memperhatikan hal-hal yang merendahkan dirinya, lalu mengangkat topik itu dan mulai mengomentarinya. Demikian '
        'pula, jika pakaiannya sudah tua, atau AC mobilnya tidak berfungsi, maka bicaralah yang baik atau diamlah. '
        'Dikisahkan bahwa seorang pria mengunjungi temannya. Temannya, sebagai tuan rumah, memberinya roti untuk dimakan '
        'dengan minyak. Tamu itu lalu berkata, "Seandainya ada za\'tar bersama roti ini!" Tuan rumah pun pergi ke '
        'keluarganya dan meminta za\'tar, namun ternyata tidak ada. Ia lalu keluar untuk membelinya, tetapi tidak punya '
        'cukup uang. Pemilik toko menolak menjualnya secara kredit. Maka ia kembali ke rumah, mengambil bejana wudhunya '
        'dan memberikannya kepada pemilik toko sebagai jaminan, agar bila tidak sanggup membayar za\'tar, pemilik toko '
        'bisa menjual bejana itu untuk menutup hutangnya. Ia lalu mengambil za\'tar dan kembali kepada tamu serta '
        'memberikannya kepadanya. Ketika tamu selesai makan, ia berkata, "Segala puji bagi Allah yang telah memberi '
        'kami makan, menghilangkan dahaga kami, dan membuat kami ridha dengan apa yang Dia berikan." Tuan rumah, '
        'mendengar ini, menghela nafas kesakitan dan berkata, "Jika Allah benar-benar telah membuatmu ridha dengan apa '
        'yang Dia berikan, tentu bejana wudhuku tidak perlu dijadikan jaminan!" Begitu pula, jika kamu menjenguk orang '
        'sakit, jangan katakan kepadanya, "Oh! Wajahmu sudah menguning! Matamu seperti mengembara! Kulitmu kering!" '
        'Betapa anehnya! Apakah kamu dokternya? Bicaralah yang baik, hanya komentarilah hal-hal yang baik, atau '
        'diamlah. Dikisahkan pula bahwa seorang pria menjenguk pasien dan duduk di sebelahnya sejenak. Ia lalu bertanya '
        'apa yang sedang dialaminya. Pasien pun memberitahu kondisinya dan bahwa sakitnya cukup parah. Sang penjenguk, '
        'mendengar ini, berteriak, "Astaga! Si Fulan, temanku, mengalami penyakit yang sama dan meninggal karenanya! '
        'Teman saudaraku juga terkena penyakit ini, dan ia terbaring hingga meninggal! Tetangga ipar saudaraku juga '
        'terkena penyakit ini dan meninggal." Sementara itu, pasien yang mendengar semua ini hampir meledak! Lalu, '
        'ketika penjenguk selesai berkata dan memutuskan untuk pergi, ia berbalik kepada pasien dan berkata, "Omong-omong, '
        'apakah kamu punya saran untukku?" Pasien menjawab, "Ya! Ketika kamu akhirnya pergi, jangan pernah kembali '
        'lagi menemuiku!" Jika kamu menjenguk pasien, jangan menyebut kematian kepadanya. Dikisahkan pula bahwa seorang '
        'wanita tua memiliki teman yang juga wanita tua, yang sedang sakit. Wanita tua itu meminta satu per satu '
        'putranya untuk mengantarnya mengunjungi temannya yang sakit, namun mereka terus membuat alasan, hingga salah '
        'satu putranya akhirnya setuju mengantarnya. Ia pun mengantarnya dengan mobilnya. Ketika tiba di rumah, '
        'wanita tua itu turun dari mobil sementara putranya menunggu. Wanita tua itu mengunjungi temannya dan mendapati '
        'temannya benar-benar dilanda penyakitnya. Ia menyapanya dan mendoakannya. Ketika hendak pergi, ia berjalan '
        'sejenak di lobi bersama putri-putri temannya yang menangis, lalu berkata dengan polos, "Sayangnya, aku tidak '
        'bisa datang sesuka hati. Ibumu sangat sakit dan sepertinya akan meninggal. Jadi biarkan aku berkata sekarang, '
        '\'Semoga Allah menganugerahkan kalian semua kesabaran yang layak atas kematiannya!\'" Hanya komentarilah '
        'hal-hal yang baik. Maka berhati-hatilah, wahai orang yang cerdas! Hanya komentarilah hal-hal yang menggembirakan, '
        'bukan yang menyedihkan. Sebuah masalah... Jika kamu terpaksa mengomentari sesuatu yang buruk, seperti kotoran '
        'pada pakaian atau bau yang tidak sedap, maka lakukanlah dengan bijaksana. Jadilah cerdas dan baik dalam '
        'melakukannya.</p>'
    ),
}

# ============================================================
# Chapter 057
# ============================================================
translations['057'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Hanya komentarilah hal-hal yang baik (29) Jangan ikut campur dalam urusan yang bukan urusanmu "Dari '
        'keindahan Islam seseorang adalah meninggalkan hal-hal yang tidak berkaitan dengannya." Betapa indahnya '
        'ungkapan ini, terlebih jika kamu mendengarnya dari mulut yang suci dan bertaqwa milik Rasulullah '
        'shallallahu \'alaihi wa sallam! Ya, meninggalkan hal-hal yang tidak berkaitan dengannya! Betapa banyak '
        'orang yang menyusahkan karena ikut campur dalam urusan yang bukan urusannya? Mereka mengganggumu ketika '
        'melihat jam tanganmu, "Berapa kamu beli ini?" Kamu menjawab, "Ini hadiah." Mereka lalu berkata, "Hadiah? '
        'Dari siapa?" Kamu menjawab, "Dari seorang teman." Ia terus bertanya, "Temanmu dari universitas? Atau dari '
        'lingkunganmu? Atau dari tempat lain?" Kamu menjawab, "Teman dari universitas." Ia terus mendesak, "Baiklah, '
        'tapi untuk acara apa?" Kamu menjawab, "Ya, suatu acara, dari masa kuliah kami." Ia lalu berkata, "Ya, tapi '
        'acara apa tepatnya? Wisuda? Atau ketika kamu pergi bersama? Atau lainnya?" Ia terus mengajukan pertanyaan '
        'tentang hal yang sama sekali tidak penting! Aku tanya kepadamu, demi Allah, bukankah kamu ingin '
        'membentaknya, "Jangan ikut campur dalam hal yang bukan urusanmu!" Dan yang lebih buruk lagi jika ia '
        'membuatmu dalam situasi canggung dengan mengajukan pertanyaan memalukan di depan umum! Aku ingat, suatu '
        'ketika aku berada dalam sebuah pertemuan bersama sekelompok teman. Setelah shalat Maghrib, salah satu '
        'telepon genggam temanku berbunyi. Ia duduk di sebelahku. Ia menjawab, "Ya?" Istrinya berteriak di telepon, '
        '"Halo! Di mana kamu, keledai?" Suaranya sangat keras sehingga aku bisa mendengar percakapan mereka dengan '
        'jelas. Ia berkata, "Aku baik-baik saja, semoga Allah menjagamu." Sepertinya ia telah berjanji mengantarnya '
        'ke keluarganya, namun menjadi sibuk bersama kami. Istrinya sangat marah dan berkata, "Semoga Allah tidak '
        'menjagamu! Kamu senang bersama teman-temanmu sementara aku menunggumu. Demi Allah, kamu itu seperti '
        'banteng!" Ia berkata, "Semoga Allah meridhaimu. Aku akan datang setelah Isya." Aku menyadari bahwa '
        'ucapannya tidak sesuai dengan ucapan istrinya. Kemudian aku menyadari bahwa ia berbicara demikian untuk '
        'menyelamatkan dirinya dari rasa malu. Ia lalu mengakhiri panggilannya. Aku mulai memandang mereka yang '
        'hadir, sambil berpikir bahwa salah satu dari mereka akan bertanya, "Siapa itu di telepon? Apa yang ia '
        'mau? Mengapa wajahmu berubah setelah percakapan itu?" Namun Allah merahmatinya; tidak ada yang ikut '
        'campur dalam urusan yang bukan milik mereka. Begitu pula, jika kamu mengunjungi pasien dan bertanya '
        'tentang sakitnya, dan ia menjawab secara samar, "Alhamdulillah, tidak terlalu berat, hanya sakit kecil," '
        'dan ungkapan-ungkapan serupa yang tidak menjawab pertanyaan secara langsung, jangan membuatnya tidak '
        'nyaman dengan terus menanyakan detail, seperti, "Maaf, tapi apa tepatnya sakitnya? Jelaskan yang kamu '
        'maksud," dan sebagainya. Mengapa perlu membuatnya malu? Dari keindahan Islam seseorang adalah meninggalkan '
        'hal yang tidak berkaitan dengannya. Maksudku, apakah kamu benar-benar menunggu ia mengatakan, "Aku '
        'mengalami wasir," atau "Aku mengalami cedera di bagian yang memalukan," dan sebagainya? Selama ia '
        'memberikan jawaban yang samar, tidak perlu meminta detail. Aku tidak bermaksud bahwa seseorang tidak '
        'boleh menanyakan kondisi pasien. Yang aku maksud adalah jangan menanyakan pertanyaan terperinci tentang '
        'penyakitnya. Contoh lain adalah seseorang yang memanggil seorang siswa di depan semua orang dalam sebuah '
        'pertemuan umum, dan bertanya dengan suara keras, "Hei! Ahmad! Apakah kamu lulus?" Ahmad berkata, "Ya." '
        'Ia bertanya, "Berapa persen? Nilai apa?" Jika ia benar-benar peduli padanya, ia akan menanyakannya saat '
        'mereka berdua saja. Tidak perlu juga masuk ke detail dengan bertanya "Berapa persen? Mengapa kamu tidak '
        'belajar? Mengapa kamu tidak diterima di universitas?" Jika ia benar-benar siap membantu, ia bisa '
        'mengajaknya ke sisi dan berbicara tentang apapun yang ia inginkan. Tapi mengumbar urusannya di depan '
        'umum bukanlah ketulusan! Nabi shallallahu \'alaihi wa sallam bersabda, "Dari keindahan Islam seseorang '
        'adalah meninggalkan hal yang tidak berkaitan dengannya." Namun berhati-hatilah. Jangan membesar-besarkan '
        'suatu hal. Suatu ketika aku bepergian ke Madinah dan sibuk menyampaikan sejumlah ceramah.</p>'
    ),
}

# ============================================================
# Chapter 058
# ============================================================
translations['058'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Maka aku menyepakati dengan seorang pemuda yang baik untuk membawa kedua putraku, \'Abd ar-Rahman dan '
        'Ibrahim, setelah Ashar, ke halaqah hafalan Qur\'an mereka, atau ke pusat hiburan musim panas, dan kembali '
        'bersama mereka setelah Isya. \'Abd ar-Rahman waktu itu berusia sepuluh tahun. Aku khawatir pemuda itu '
        'mungkin menanyainya hal-hal yang tidak berguna, seperti, "Siapa nama ibumu? Di mana rumahmu? Berapa '
        'saudaramu? Berapa uang jajan yang diberikan ayahmu?" Maka aku memperingatkan \'Abd ar-Rahman dan berkata, '
        '"Jika ia menanyaimu pertanyaan yang tidak pantas, katakan saja kepadanya bahwa Nabi shallallahu \'alaihi '
        'wa sallam bersabda, \'Dari keindahan Islam seseorang adalah meninggalkan hal yang tidak berkaitan '
        'dengannya.\'" Aku mengulangi hadits itu kepadanya hingga ia menghafalnya. \'Abd ar-Rahman dan adiknya '
        'kemudian duduk di mobil bersama pemuda itu. \'Abd ar-Rahman pada saat itu sangat tegang sekaligus '
        'bersikap hormat. Pemuda itu berkata dengan ramah, "Semoga Allah memanjangkan umurmu, wahai \'Abd '
        'ar-Rahman!" \'Abd ar-Rahman menjawab, "Semoga Allah memanjangkan umurmu juga!" Pemuda malang itu ingin '
        'sedikit mencairkan suasana, lalu berkata, "Apakah Syekh hari ini menyampaikan ceramah?" \'Abd ar-Rahman '
        'mencoba mengingat haditsnya, namun ingatannya tidak membantunya, maka ia pun berteriak, "Jangan ikut '
        'campur dalam hal yang bukan urusanmu!" Pemuda itu berkata, "Maksudku, aku hanya ingin menghadiri '
        'ceramahnya dan mengambil manfaat." \'Abd ar-Rahman mengira ia sedang mencoba menjadi cerdik, maka ia '
        'mengulangi jawaban yang sama, "Jangan ikut campur dalam hal yang bukan urusanmu." Pemuda itu berkata, '
        '"Maaf, \'Abd ar-Rahman. Maksudku adalah..." namun \'Abd ar-Rahman kembali berteriak, "Tidak! Jangan '
        'ikut campur dalam hal yang bukan urusanmu!" Mereka terus begitu hingga aku kembali. \'Abd ar-Rahman '
        'lalu menceritakan kisah lengkapnya kepadaku dengan bangga, maka aku pun tertawa dan harus menjelaskan '
        'konsepnya lagi kepadanya. Latihan... Berjuang melawan diri sendiri untuk membebaskan diri dari ikut '
        'campur dalam urusan orang lain memang melelahkan di awal, namun mudah pada akhirnya. Jangan ikut campur '
        'dalam urusan yang bukan urusanmu (30) Cara menghadapi orang yang suka ikut campur Terkadang, beberapa '
        'orang mungkin mengambil ponselmu tanpa izin dan mulai membaca pesan-pesanmu. Seorang teman saya diundang '
        'ke pesta pernikahan seorang hakim, dan hampir semua tamunya adalah para ulama terkemuka. Temanku duduk '
        'di antara mereka dan terlibat dalam percakapan yang dalam. Sementara itu, keberadaan telepon genggam '
        'di sakunya membuatnya tidak nyaman, sehingga ia memutuskan untuk mengeluarkannya dan meletakkannya di '
        'atas meja di sebelahnya. Ulama terhormat yang duduk di sebelahnya sangat terlibat dalam percakapan '
        'dengannya. Tanpa disadari, ulama terhormat itu mengambil telepon genggam yang ada di atas meja, dan '
        'ketika ia melihat layarnya, wajahnya berubah lalu ia mengembalikan telepon genggam itu ke tempat semula. '
        'Temanku memperhatikan hal itu dan berusaha keras menahan tawanya. Ketika ia meninggalkan pesta, aku '
        'duduk bersamanya di mobilnya. Ia meletakkan ponselnya di sampingnya. Kebetulan aku mengambil ponsel '
        'itu, seperti yang dilakukan ulama terhormat di pesta pernikahan itu, dan ketika aku melihat layarnya, '
        'aku tertawa terbahak-bahak. Tahukah kamu mengapa? Banyak orang menulis berbagai pesan di layar ponsel '
        'mereka, seperti namanya, atau \'Ingat Allah\', dan sebagainya. Adapun temanku, ia menulis, \'Kembalikan '
        'ponselnya, kamu orang yang usil!\' Banyak orang seperti itu cenderung ikut campur dalam urusan pribadi '
        'orang lain. Sehingga menjadi kebiasaan bagi mereka untuk duduk di mobil bersamamu, membuka laci dasbor '
        'dan melihat isinya! Wanita yang suka ikut campur akan mengintip ke dalam tas wanita lain untuk mengambil '
        'lipstik atau perona matanya. Salah satu dari mereka mungkin meneleponmu dan bertanya di mana kamu. '
        'Ketika kamu berkata, "Aku ada urusan," ia akan bertanya, "Di mana? Siapa yang bersamamu?" dan seterusnya. '
        'Beberapa orang yang bergaul dengan kita sering memperlakukan kita seperti itu. Bagaimana cara menghadapi '
        'mereka? Salah satu hal terpenting yang tidak boleh kamu lupakan adalah berusaha menghindari orang itu '
        'sebisa mungkin. Pastikan tidak ada yang merasa kecewa dalam prosesnya. Bersikaplah diplomatik sambil '
        'melepaskan diri dari situasi seperti itu tanpa menciptakan masalah di antara kalian. Menambah musuh '
        'atau kehilangan teman tidak boleh dianggap sepele, apapun penyebabnya. Salah satu cara terbaik '
        'menghadapi orang yang suka ikut campur adalah dengan merespons pertanyaan dengan pertanyaan lain, atau '
        'mengganti topik pembicaraan sepenuhnya, sehingga membuatnya lupa pertanyaan yang ia ajukan.</p>'
    ),
}

# ============================================================
# Chapter 060
# ============================================================
translations['060'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Teman-teman terdekat mereka tidak menyukai mereka dan menghindari kebersamaan dengan mereka. '
        'SubhanAllah! Padahal Allah berfirman, "Dan apabila kamu berbicara, berlaku adillah!" Ibu kita \'A\'isyah '
        'radhiyallahu \'anha berkata, ketika menggambarkan cara Rasulullah shallallahu \'alaihi wa sallam '
        'memperlakukan orang lain, "Rasulullah shallallahu \'alaihi wa sallam tidak pernah mengeluh tentang '
        'makanan. Jika beliau menyukainya, beliau memakannya. Jika tidak menyukainya, beliau cukup '
        'meninggalkannya." (Al-Bukhari dan Muslim) Benar! Beliau tidak pernah ribut soal apapun. Anas '
        'radhiyallahu \'anhu berkata, "Aku melayani Rasulullah shallallahu \'alaihi wa sallam selama sembilan '
        'tahun. Aku tidak pernah mendengar beliau mengomentari apa yang aku lakukan, \'Mengapa kamu melakukan '
        'ini?!\' Beliau tidak pernah mengkritiku sedikitpun. Demi Allah! Beliau bahkan tidak pernah berkata '
        '\'uf\' kepadaku!" Inilah cara beliau, dan inilah cara kita seharusnya. Namun dengan mengatakan itu, '
        'aku tidak menyarankan kamu untuk tidak menasihati orang lain, atau untuk diam atas kesalahan mereka. '
        'Sebaliknya, janganlah kamu memeriksa segala sesuatu yang dilakukan orang, terutama dalam urusan '
        'duniawi. Belajarlah untuk mengabaikan hal-hal seperti itu. Jika seorang tamu mengetuk pintumu, kamu '
        'menyambutnya dan mengajaknya ke ruang tamu. Ketika kamu membawakan teh, ia mengambil cangkir teh. '
        'Setelah melihat ke dalam cangkir, ia mengomentari, "Mengapa kamu tidak mengisi penuh cangkirnya?" '
        'Jika kamu berkata, "Apakah aku perlu menambahkan?" Ia berkata, "Tidak, biarkan saja. Ini sudah cukup." '
        'Ia lalu meminta air dan kamu memberinya segelas air yang ia minum. Setelah selesai, ia berkata, '
        '"Airnya agak hangat." Ia lalu berpaling ke AC dan berkata, "AC kamu sepertinya tidak berfungsi!" '
        'dan mulai mengeluh tentang panasnya. Tidakkah kamu merasa orang ini sangat menyusahkan, dan berharap '
        'ia pergi dan tidak pernah kembali? Orang tidak suka dikritik terlalu banyak. Namun, jika kamu memang '
        'harus mengkritik, maka kemaslah dengan baik dan sampaikan dengan kebaikan kepada orang lain. '
        'Sampaikan seolah-olah itu adalah saran, bukan kritikan. Sampaikan secara tidak langsung, atau '
        'menggunakan ungkapan yang samar. Jika Rasulullah shallallahu \'alaihi wa sallam pernah melihat '
        'seseorang melakukan kesalahan, beliau tidak langsung menghadapinya. Sebaliknya, beliau berkata, '
        '"Ada apa dengan orang-orang yang melakukan hal seperti ini?" yang secara tidak langsung berarti, '
        '"Yang kumaksud adalah kamu, wahai tetangga, maka perhatikanlah!" Suatu ketika, tiga pemuda bersemangat '
        'pergi ke Madinah, ingin mengetahui persis bagaimana Nabi shallallahu \'alaihi wa sallam beribadah '
        'dan menunaikan shalatnya. Mereka bertanya kepada para istri Nabi tentang apa yang beliau lakukan '
        'secara pribadi. Para istri beliau lalu memberitahu mereka bahwa terkadang beliau berpuasa dan '
        'terkadang tidak. Beliau juga tidur sebagian malam dan shalat di sebagian lainnya. Mereka lalu '
        'berkata satu sama lain, "Tapi ini adalah Rasulullah yang dosa-dosanya yang lalu telah diampuni '
        'Allah." Lalu masing-masing dari mereka membuat keputusan. Salah satu berkata, "Aku tidak akan '
        'menikah. Aku akan tetap bujang dan dengan demikian bebas untuk beribadah." Yang lain berkata, '
        '"Aku akan selalu berpuasa, setiap hari." Yang ketiga berkata, "Aku tidak akan tidur di malam hari. '
        'Aku akan shalat sepanjang malam." Ketika berita ini sampai kepada Nabi shallallahu \'alaihi wa '
        'sallam, beliau berdiri di mimbarnya, memuji dan mengagungkan Allah, lalu berkata, "Ada apa dengan '
        'orang-orang?" perhatikan ungkapan yang samar itu. Beliau tidak berkata, "Ada apa dengan si Fulan?" '
        'Sebaliknya, beliau berkata, "Ada apa dengan orang-orang yang mengatakan begini dan begitu? Padahal, '
        'aku shalat dan tidur. Aku berpuasa dan kadang tidak. Aku juga menikahi wanita. Barangsiapa yang '
        'berpaling dari sunnahku, ia bukan golonganku." (Al-Bukhari dan Muslim) Pada kesempatan lain, Nabi '
        'shallallahu \'alaihi wa sallam memperhatikan bahwa sebagian orang yang shalat bersamanya mengangkat '
        'mata ke langit saat shalat. Ini tidak benar, karena seseorang seharusnya memandang tempat sujud '
        'saat shalat. Beliau berkata, "Ada apa dengan orang-orang yang mengangkat mata mereka ke langit '
        'dalam shalat mereka?" Ketika mereka tidak berhenti dari hal itu dan terus mendongak, beliau tidak '
        'mempermalukan mereka, atau menyebut nama mereka. Sebaliknya, beliau berkata, "Mereka harus berhenti, '
        'atau penglihatan mereka akan dirampas." (Al-Bukhari) Bareerah adalah seorang budak wanita di Madinah. '
        'Ia ingin dimerdekakan, sehingga meminta pemiliknya untuk memerdekakannya. Pemiliknya mensyaratkan '
        'bahwa ia membayar uang tebusan untuk kemerdekaannya. Bareerah lalu datang kepada \'A\'isyah untuk '
        'meminta bantuan keuangan. \'A\'isyah berkata, "Jika kamu mau, aku bisa membayar hargamu kepada '
        'pemilikmu agar kamu merdeka, dengan syarat loyalitasmu ada padaku." Budak wanita itu menginformasikan '
        'hal ini kepada pemiliknya, namun mereka menolak. Mereka ingin mendapat keuntungan ganda; mereka '
        'menginginkan uang tebusannya sekaligus utang loyalitasnya.</p>'
    ),
}

# ============================================================
# Chapter 061
# ============================================================
translations['061'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>\'A\'isyah lalu bertanya kepada Nabi shallallahu \'alaihi wa sallam dan beliau pun terkejut dengan '
        'kecintaan mereka terhadap harta, dan penolakan mereka untuk membiarkan wanita miskin ini merdeka! '
        'Beliau berkata kepada \'A\'isyah, "Belilah ia, lalu merdekakanlah. Sesungguhnya loyalitas hanya '
        'untuk orang yang memerdekakan budak." Artinya, loyalitas selalu menjadi milikmu selama kamu yang '
        'membayar, dan jangan khawatir tentang syarat-syarat mereka karena itu tidak adil. Kemudian Nabi '
        'shallallahu \'alaihi wa sallam berdiri di mimbarnya dan berkata, "Ada apa dengan orang-orang," '
        'dan beliau tidak berkata, "Ada apa dengan keluarga si fulan?" Nabi shallallahu \'alaihi wa sallam '
        'melanjutkan, "...yang mereka mensyaratkan syarat-syarat yang tidak ada dalam Kitab Allah? Barangsiapa '
        'mensyaratkan syarat yang tidak ada dalam Kitab Allah, maka ia tidak berhak atas terpenuhinya syarat '
        'itu, meskipun ia mensyaratkan seratus syarat seperti itu!" (Al-Bukhari dan Muslim) Ya! Beginilah '
        'cara beliau mengatakannya. Beliau mengayunkan tongkat dari jauh, namun tidak memukul apapun '
        'dengannya. Apa yang lebih baik bagimu daripada mengatakan kepada istrimu, yang tidak menjaga '
        'kebersihan rumah, "Kemarin, kami menginap di rumah temanku, dan semua orang memuji kebersihannya." '
        'Apa yang lebih baik daripada mengatakan kepada putramu, yang tidak shalat di masjid, "Aku kagum '
        'dengan orang ini di lingkungan kita! Sepertinya aku tidak pernah luput melihatnya di masjid sama '
        'sekali!" Artinya, "Yang kumaksud adalah kamu, maka perhatikanlah!" Wajar jika kamu bertanya mengapa '
        'orang tidak suka dikritik, dan aku akan menjawab, "Karena kritik membuat mereka merasa kurang '
        'sempurna. Setiap orang mencintai kesempurnaan." Dikisahkan bahwa suatu ketika seorang pria yang '
        'sangat sederhana ingin memegang kendali. Untuk itu ia mengambil dua termos, satu hijau dan satu '
        'merah. Ia mengisi keduanya dengan air dingin. Ia kemudian duduk di jalan orang-orang dan mulai '
        'berteriak, "Air dingin, gratis!" Mereka yang haus akan datang kepadanya, mengambil gelas dan '
        'menuangkan air untuk diri mereka sendiri. Ketika pria ini melihat bahwa orang yang haus ingin '
        'minum dari termos hijau, ia berkata, "Tidak! Minumlah dari yang merah." Maka ia minum dari yang '
        'merah. Ketika orang lain datang yang ingin minum dari yang merah, ia berkata, "Tidak! Minumlah '
        'dari yang hijau!" Jika seseorang keberatan dan bertanya, "Apa bedanya keduanya?!" Ia berkata, '
        '"Akulah yang bertanggung jawab atas airnya. Terimalah apa yang ada, atau cari air di tempat lain!" '
        'Dorongan yang terus-menerus dalam diri seseorang untuk diakui dan dianggap penting itulah yang '
        'menggerakkannya. Lebah dan lalat... Jadilah seperti lebah yang mencari aroma harum dan mengabaikan '
        'kotoran. Jangan seperti lalat yang mencari luka berdarah. Jangan mengkritik! (32) Jangan bersikap '
        'diktator Bandingkan tiga ayah. Masing-masing dari mereka melihat anaknya duduk di depan layar '
        'televisi di hari-hari ujiannya. Yang pertama berkata kepada anaknya, "Muhammad! Ulangi pelajaranmu!" '
        'Yang kedua berkata, "Majid! Jika kamu tidak belajar, demi Allah, aku akan memukulmu dan tidak akan '
        'memberimu uang jajan!" Yang ketiga berkata, "Shalih! Maukah kamu belajar? Itu lebih baik daripada '
        'menonton televisi, bukan?" Manakah dari ketiganya yang dianggap bersikap paling baik? Tidak '
        'diragukan lagi, yang ketiga, karena ia menyampaikan perintahnya seolah-olah hanya saran. Begitu '
        'pula seharusnya ketika berurusan dengan istrimu. "Sarah, bisakah kamu membuatkan secangkir teh?" '
        '"Hind, aku ingin makan siang lebih awal hari ini, jika memungkinkan." Demikian pula, ketika '
        'seseorang berbuat salah, cobalah memperbaikinya dengan cara yang membuatnya berpikir bahwa '
        'perbaikan itu adalah inisiatifnya sendiri. Misalnya, putramu sering tidak hadir untuk shalat '
        'di masjid. Kamu bisa berkata kepadanya, misalnya, "Sa\'d, bukankah kamu ingin masuk surga? '
        'Tentu saja! Kalau begitu, kamu harus menjaga shalatmu." Suatu ketika, di tenda Badui di padang '
        'pasir, seorang wanita merintih saat melahirkan. Suaminya berada di sampingnya, menunggu kelahiran '
        'bayinya. Rasa sakit persalinan menjadi semakin parah bagi wanita itu, dan akhirnya ia melahirkan, '
        'namun bayi yang lahir berkulit hitam! Pria itu memandang dirinya sendiri dan istrinya, keduanya '
        'berkulit putih. Ia heran bagaimana putranya bisa berkulit hitam. Setan membisikkan ke hatinya, '
        '"Mungkin bayi ini milik orang lain. Mungkin seorang pria berkulit hitam berzina dengannya, '
        'sehingga ia mengandung! Mungkin..." Pria itu kebingungan dan pergi ke Madinah menemui Rasulullah '
        'shallallahu \'alaihi wa sallam yang sedang duduk bersama para sahabatnya.</p>'
    ),
}

# ============================================================
# Chapter 062
# ============================================================
translations['062'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Ia berkata, "Wahai Rasulullah! Istriku melahirkan seorang anak yang berkulit hitam! Kami tidak '
        'pernah memiliki siapapun yang berkulit hitam dalam keluarga kami!" Nabi shallallahu \'alaihi wa '
        'sallam memandangnya. Meskipun beliau sangat bisa memberikan kuliah kepadanya tentang berprasangka '
        'baik kepada orang lain, dan bahwa ia seharusnya tidak menuduh istrinya, beliau memutuskan untuk '
        'mencoba metode yang berbeda dengannya untuk memecahkan masalahnya. Beliau memutuskan untuk membuat '
        'pria itu memecahkan masalahnya sendiri. Beliau memutuskan untuk memberinya contoh-contoh yang '
        'dengannya ia bisa dengan mudah menemukan jawaban atas masalahnya sendiri. Namun contoh seperti apa '
        'yang harus beliau berikan? Contoh pohon-pohon? Atau lebah? Atau orang Persia dan Romawi? Nabi '
        'shallallahu \'alaihi wa sallam memandangnya dan melihat bahwa ia adalah seorang Badui yang terlihat '
        'sangat bingung karena semua pikiran yang datang ke benaknya tentang istrinya. Nabi shallallahu '
        '\'alaihi wa sallam berkata, "Apakah kamu memiliki unta?" Jangan bersikap diktator "Ya," kata pria '
        'itu. Nabi shallallahu \'alaihi wa sallam berkata, "Apa warnanya?" Ia berkata, "Merah." Nabi '
        'shallallahu \'alaihi wa sallam berkata, "Apakah ada yang berwarna hitam di antara mereka?" "Tidak," '
        'ia menjawab. Nabi shallallahu \'alaihi wa sallam berkata, "Apakah ada yang berwarna abu-abu di '
        'antara mereka?" "Ya," jawab pria itu. Nabi shallallahu \'alaihi wa sallam berkata, "Dari mana '
        'warna itu datang?" Artinya, selama semuanya merah, jantan dan betina, dan tidak satupun dari '
        'mereka berwarna berbeda, bagaimana seekor unta merah bisa melahirkan unta abu-abu yang berbeda '
        'dari induk dan ayahnya? Pria itu berpikir sejenak dan berkata, "Mungkin karena keturunan." '
        'Artinya, mungkin salah satu nenek moyangnya berwarna abu-abu. Maka warna abu-abu itu tetap ada '
        'dalam garis keturunan, dan diwarisi oleh anak unta ini. Kemudian Nabi shallallahu \'alaihi wa '
        'sallam berkata, "Mungkin putramu juga mewarisi warna ini karena keturunan." (Muslim dan Ibnu '
        'Majah) Pria itu mendengar jawabannya, berpikir sejenak dan menemukan bahwa ia sendiri yang sampai '
        'pada kesimpulan itu. Ia merasa puas dan yakin dengan jawabannya, lalu kembali kepada istrinya. '
        'Pada kesempatan lain, Nabi shallallahu \'alaihi wa sallam duduk bersama para sahabatnya dan '
        'mulai memberitahu mereka tentang berbagai amal kebaikan. Di antara hal-hal yang beliau sebutkan '
        'adalah bahwa beliau bersabda, "Dalam hubungan intim salah seorang dari kalian terdapat sedekah"; '
        'artinya, bagi salah seorang dari kalian untuk berhubungan intim dengan istrinya adalah perbuatan '
        'yang mendapat pahala dari Allah. Jangan bersikap diktator Mendengar hal ini, para sahabat terkejut '
        'dan berkata, "Wahai Rasulullah, salah seorang dari kami mendatangi istrinya untuk memenuhi '
        'kebutuhannya, dan untuk itu ia akan mendapat pahala?" Nabi shallallahu \'alaihi wa sallam lalu '
        'merespons dengan cara yang membuat mereka merasa merekalah yang menemukan jawabannya sendiri, '
        'sehingga tidak perlu diskusi lebih lanjut untuk meyakinkan mereka. Nabi shallallahu \'alaihi '
        'wa sallam berkata, "Bukankah kamu melihat bahwa jika ia melakukannya dengan cara yang haram, '
        'ia akan berdosa?" Mereka berkata, "Ya." "Maka jika ia melakukannya dengan cara yang halal, '
        'ia akan mendapat pahala," kata Nabi shallallahu \'alaihi wa sallam. Bahkan saat berdiskusi '
        'dengan orang lain pun, beliau akan memandu mereka menuju jawaban dengan memulai dari hal-hal '
        'yang keduanya sepakati. Nabi shallallahu \'alaihi wa sallam pernah berangkat ke Makkah bersama '
        'seribu empat ratus sahabatnya, namun kaum Quraisy memblokir jalannya. Ini mengarah pada peristiwa '
        'Al-Hudaybiyyah yang terkenal, di mana setelah sesi diskusi panjang antara Nabi dan kaum Quraisy, '
        'mereka menyepakati perjanjian damai. Suhail bin \'Amr adalah perwakilan Quraisy saat menulis '
        'kondisi perjanjian. Nabi shallallahu \'alaihi wa sallam menyepakati Suhail dalam beberapa kondisi, '
        'dan di antaranya adalah: - Kaum muslimin harus kembali ke Madinah tanpa melaksanakan Umrah - '
        'Kaum muslimin di Madinah tidak boleh menerima siapapun yang ingin masuk Islam dari penduduk '
        'Makkah dan memutuskan untuk berhijrah ke Madinah. Jangan bersikap diktator - Siapapun yang '
        'meninggalkan Islam dan memutuskan pergi ke orang-orang musyrik di Makkah akan diterima. Ada '
        'banyak kondisi lain yang tampaknya merupakan tanda kekalahan dan penghinaan kaum muslimin. '
        'Padahal, kaum Quraisy sebenarnya takut dengan jumlah kaum muslimin yang begitu besar, dan '
        'menyadari bahwa jika mereka mau, mereka bisa dengan mudah menaklukkan Makkah. Karena alasan '
        'inilah kaum Quraisy terpaksa bersikap diplomatik. Mereka tidak bisa bermimpi bahwa mereka akan '
        'berhasil lolos dengan seperempat dari syarat-syarat itu. Sebagian besar sahabat tidak nyaman '
        'dengan syarat-syarat ini. Namun bagaimana mereka bisa memprotes? Yang menulis kontrak dan '
        'menyetujui kondisi-kondisinya adalah orang yang tidak berbicara dari hawa nafsunya. Umar sangat '
        'gundah. Ia melihat ke kanan dan ke kiri, berharap seandainya ia bisa berbuat sesuatu. Umar '
        'segera mendekati Abu Bakr untuk mendiskusikan hal ini dengannya. Karena kebijaksanaannya, ia '
        'tidak memulai dengan memprotes. Sebaliknya, ia memulai dengan hal-hal yang keduanya sepakati.</p>'
    ),
}

# ============================================================
# Chapter 063
# ============================================================
translations['063'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Maka ia mulai mengajukan pertanyaan-pertanyaan kepada Abu Bakr, yang jawabannya tidak lain '
        'adalah, "Benar! Ya! Tepat!" Ia berkata, "Wahai Abu Bakr, bukankah ia adalah Rasulullah?" '
        '"Benar, ia adalah!" kata Abu Bakr. Ia berkata, "Bukankah kita adalah orang-orang Muslim?" '
        '"Benar, kita adalah!" jawab Abu Bakr. Ia berkata, "Bukankah mereka adalah orang-orang musyrik?" '
        '"Tentu saja!" jawab Abu Bakr. Umar berkata, "Bukankah kita berada di atas kebenaran?" Jangan '
        'bersikap diktator "Benar, kita adalah!" jawab Abu Bakr. Umar berkata, "Bukankah mereka berada '
        'di atas kebatilan?" "Tentu saja!" jawab Abu Bakr. Umar berkata, "Mengapa kita harus menyerah '
        'dalam hal yang berkaitan dengan agama kita?" Abu Bakr lalu berkata, "Wahai Umar, bukankah ia '
        'adalah Rasulullah?" "Tentu saja," kata Umar. Abu Bakr berkata, "Maka taatilah ia! Karena aku '
        'bersaksi bahwa ia adalah Rasulullah." Umar lalu berkata, "Aku juga bersaksi bahwa ia adalah '
        'Rasulullah," dan pergi. Ia mencoba menahan diri namun tidak bisa, sehingga ia mendekati '
        'Rasulullah shallallahu \'alaihi wa sallam. Ia berkata, "Wahai Rasulullah, bukankah engkau '
        'adalah Rasulullah?" "Benar, aku adalah!" kata Nabi shallallahu \'alaihi wa sallam. Ia berkata, '
        '"Bukankah kita adalah orang-orang Muslim?" "Tentu saja, kita adalah," kata Nabi shallallahu '
        '\'alaihi wa sallam. Ia berkata, "Bukankah mereka adalah orang-orang musyrik?" "Ya, mereka '
        'adalah," jawab Nabi shallallahu \'alaihi wa sallam. Ia berkata, "Lalu mengapa kita berkompromi '
        'dalam hal yang berkaitan dengan agama?" Nabi shallallahu \'alaihi wa sallam lalu berkata, '
        '"Aku adalah hamba Allah dan Rasul-Nya. Aku tidak akan melanggar perintah-Nya. Dia tidak akan '
        'pernah menyesatkanku." Umar terdiam. Perjanjian ditandatangani, dan kaum muslimin kembali '
        'ke Madinah. Hari-hari berlalu dan kaum Quraisy melanggar perjanjian. Nabi shallallahu \'alaihi '
        'wa sallam kemudian menaklukkan Makkah dan membersihkan Ka\'bah dari berhala-berhala. Kemudian, '
        'Umar menyadari bahwa ia salah dalam menentang keputusan Nabi shallallahu \'alaihi wa sallam. '
        'Karena itulah ia selalu berkata, "Aku tidak pernah berhenti berpuasa, bersedekah, shalat dan '
        'membebaskan budak, karena apa yang aku lakukan hari itu, mengkhawatirkan akibat dari kata-kata '
        'yang aku ucapkan hari itu, hingga aku mulai mendapatkan kembali harapan." Betapa mulianya Umar! '
        'Betapa mulianya Rasulullah shallallahu \'alaihi wa sallam sebelumnya! Bagaimana kita bisa '
        'memanfaatkan keterampilan ini? Jika putramu tidak menghafal Al-Qur\'an, dan kamu ingin ia '
        'melakukannya dengan semangat, maka mulailah dengan hal-hal yang kalian berdua sepakati. Kamu '
        'bisa berkata kepadanya, "Bukankah kamu ingin Allah mencintaimu? Bukankah kamu ingin meninggikan '
        'derajatmu di Surga?" Tidak diragukan ia akan menjawab, "Benar!" Kemudian, kamu bisa '
        'menyampaikan nasihatmu sebagai saran, berkata, "Kalau begitu, jika kamu menghadiri halaqah '
        'hafalan Al-Qur\'an..." Begitu pula, jika kamu melihat seorang wanita yang tidak memakai hijab, '
        'bicaralah kepadanya tentang hal-hal yang kalian berdua sepakati. Kamu harus berkata, "Aku tahu '
        'kamu adalah seorang muslimah, dan karena itu, selalu bersemangat melakukan kebaikan." Ia akan '
        'berkata, "Benar, alhamdulillah." Kamu selanjutnya berkata, "Kamu adalah wanita yang suci yang '
        'mencintai Allah." Jangan bersikap diktator Ia akan berkata, "Ya, alhamdulillah." Kemudian, '
        'kamu bisa menyampaikan nasihatmu dalam bentuk saran, berkata, "Mungkin kamu harus lebih '
        'memperhatikan aspek hijab dalam Islam, dan menunjukkan lebih banyak semangat untuk menutupi '
        'diri." Inilah cara kita mendapatkan apa yang kita inginkan dari orang-orang, tanpa mereka '
        'menyadarinya. Sekilas... Kamu selalu bisa makan madu tanpa menghancurkan sarangnya. Jangan '
        'bersikap diktator (33) Pegang tongkat dari tengahnya "Terima kasih banyak karena memilih '
        'mengajar sebagai karier. Allah telah menganugerahimu dengan bakat mengajar. Murid-muridmu '
        'sangat mencintaimu. Namun, aku berharap kamu tidak terlambat datang ke tempat kerja di pagi '
        'hari." "Kamu cantik. Rumahmu rapi. Aku tidak memungkiri bahwa anak-anak itu melelahkanmu. '
        'Namun, seandainya kamu bisa lebih memperhatikan pakaian mereka." Inilah cara orang yang '
        'shalih bersikap terhadap orang-orang. Ia menyebutkan hal-hal baik terlebih dahulu kemudian '
        'mengarahkan perhatiannya pada kekurangan, agar pendekatan yang digunakan seimbang. Ketika '
        'kamu mengkritik, cobalah menyebutkan di mana seseorang benar sebelum menyebutkan di mana ia '
        'salah. Selalu cobalah memberikan kesan bahwa kamu memiliki pandangan positif tentangnya. '
        'Ketika kamu memperingatkannya atas kesalahannya, ini tidak berarti kamu meremehkannya, atau '
        'bahwa kamu telah melupakan amal baiknya, atau bahwa kamu hanya boleh menyebutkan hal-hal '
        'salahnya. Sebaliknya, buatlah ia menyadari bahwa kritikanmu terhadapnya tidak berarti '
        'dibandingkan dengan amal baiknya. Nabi shallallahu \'alaihi wa sallam sangat dicintai di '
        'antara para sahabatnya. Beliau menggunakan teknik-teknik yang luar biasa saat berurusan '
        'dengan mereka. Suatu ketika beliau berdiri bersama para sahabatnya dan memandang langit, '
        'seolah merenungi atau mencari sesuatu.</p>'
    ),
}

# ============================================================
# Chapter 064
# ============================================================
translations['064'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Beliau lalu berkata, "Ini adalah musim di mana ilmu akan dirampas dari manusia, hingga mereka '
        'tidak akan memiliki sedikitpun darinya"; artinya, orang-orang akan berpaling dari Al-Qur\'an, '
        'ajaran-ajarannya, dan Ilmu Agama. Mereka tidak akan menunjukkan semangat untuk memperolehnya, '
        'juga tidak akan memahaminya. "...dirampas dari mereka..." artinya akan diambil dari mereka. '
        'Mendengar hal ini, seorang sahabat mulia berdiri – ia adalah Ziyad bin Labid Al-Ansari – dan '
        'berkata dengan penuh semangat, "Wahai Rasulullah, bagaimana mungkin ia dirampas dari kita? '
        'Kita telah membaca Al-Qur\'an! Demi Allah, kita akan terus membacanya! Kita akan membuat '
        'istri dan anak-anak kita membacanya!" Nabi shallallahu \'alaihi wa sallam memandangnya dan '
        'menemukan ia adalah seorang pemuda yang penuh semangat dan antusias terhadap agama. Beliau '
        'lalu memutuskan untuk meluruskan pemahamannya, sehingga beliau berkata, "Semoga ibumu '
        'berduka atasmu, wahai Ziyad! Meskipun, aku benar-benar menganggapmu termasuk di antara '
        'para fuqaha penduduk Madinah!" Ini adalah pujian bagi Ziyad, karena Rasulullah shallallahu '
        '\'alaihi wa sallam berkata kepadanya di depan orang-orang bahwa ia termasuk di antara para '
        'fuqaha Madinah. Ini adalah salah satu halaman positif dan cerah dari kehidupan Ziyad. '
        'Beliau kemudian berkata, "Orang-orang Yahudi dan Nasrani memiliki Taurat dan Injil. Apa '
        'manfaatnya bagi mereka?" (Shahih – diriwayatkan oleh At-Tirmidzi dan Al-Hakim) Artinya, '
        'bukan keberadaan Al-Qur\'an yang penting. Yang penting adalah bacaannya, pengetahuan akan '
        'maknanya, dan kemudian mengamalkan hukum-hukumnya. Inilah betapa agungnya cara Nabi '
        'shallallahu \'alaihi wa sallam dalam berurusan dengan orang-orang. Pegang tongkat dari '
        'tengahnya Pada kesempatan lain, Nabi shallallahu \'alaihi wa sallam mendatangi beberapa '
        'suku Arab untuk menyeru mereka kepada Islam. Beliau akan memilih kata-kata yang paling '
        'indah untuk mendorong mereka merespons seruannya dan masuk ke dalam Islam. Salah satu '
        'suku yang beliau datangi dikenal sebagai Banu \'Abdullah. Ketika Nabi shallallahu \'alaihi '
        'wa sallam menyeru mereka kepada Allah dan menyampaikan pesannya kepada mereka, beliau '
        'berkata, "Wahai Banu \'Abdullah! Allah telah memilihkan nama yang indah bagi ayah kalian!"; '
        'artinya, kalian bukan Banu \'Abd Al-\'Izza, atau Banu \'Abd Al-Laat. Sebaliknya, kalian '
        'adalah Banu \'Abdullah. Syukurlah, tidak ada kemusyrikan dalam nama kalian, dan karena '
        'itu, kalian seharusnya masuk ke dalam Islam. Bahkan, beliau sangat mahir dalam caranya '
        'sehingga beliau mengirimkan pesan-pesan tidak langsung kepada orang-orang, menunjukkan '
        'kekagumannya kepada mereka, dan bahwa beliau menginginkan kebaikan bagi mereka. Ketika '
        'pesan-pesan tidak langsung seperti itu sampai kepada orang-orang yang dituju, mungkin '
        'pesan-pesan itu akan lebih mempengaruhi mereka daripada pesan-pesan langsung. Khalid bin '
        'Al-Walid radhiyallahu \'anhu adalah seorang pahlawan. Ia bukan pahlawan sembarang, '
        'melainkan pahlawan yang pemberani. Nabi shallallahu \'alaihi wa sallam berharap ia '
        'memeluk Islam. Namun bagaimana caranya? Karena ia sangat bersemangat untuk terlibat '
        'dalam setiap pertempuran melawan kaum muslimin. Bahkan, ia adalah alasan terbesar kekalahan '
        'kaum muslimin dalam Perang Uhud. Nabi shallallahu \'alaihi wa sallam pernah mengatakan '
        'tentang dirinya, "Jika ia datang kepada kami, kami pasti akan memuliakannya dan '
        'mengutamakannya dari yang lain." Bagaimana hal ini mempengaruhinya? Mari kita kutip '
        'kisahnya dari awal. Khalid adalah salah satu dari orang-orang kafir yang paling keras '
        'Pegang tongkat dari tengahnya dan salah satu pemimpin mereka. Ia tidak akan pernah '
        'melewatkan kesempatan untuk memerangi Rasulullah shallallahu \'alaihi wa sallam atau '
        'menyergapnya. Ketika Nabi shallallahu \'alaihi wa sallam datang ke Al-Hudaybiyyah bersama '
        'kaum muslimin dengan niat melaksanakan Umrah, Khalid bersama para ksatria musyrik lainnya '
        'berangkat dan bertemu Nabi shallallahu \'alaihi wa sallam dan para sahabatnya di suatu '
        'tempat yang disebut \'Asfaan. Khalid berdiri dekat dengan mereka, hanya menunggu kesempatan '
        'untuk menyerang Rasulullah shallallahu \'alaihi wa sallam dengan panah atau pedang. Maka '
        'ia mulai menunggu kesempatan untuk menyergap. Nabi shallallahu \'alaihi wa sallam shalat '
        'subuh bersama para sahabatnya sementara musuh-musuh menyaksikan. Mereka ingin menyerang '
        'beliau, namun tidak menemukan kesempatan yang tepat. Nabi shallallahu \'alaihi wa sallam '
        'menyadari niat mereka dan karena itu shalat Ashar bersama para sahabatnya sebagai shalat '
        'khauf; artinya, beliau membagi para sahabatnya menjadi dua kelompok. Satu kelompok shalat '
        'bersamanya sementara kelompok lain berjaga. Ini sangat mempengaruhi Khalid dan para '
        'sahabatnya. Ia berkata dalam hatinya, "Laki-laki itu dilindungi dari kita," artinya, '
        'ada orang-orang yang akan melindungi dan membelanya dari bahaya. Kemudian Nabi shallallahu '
        '\'alaihi wa sallam bersama para sahabatnya berangkat mengambil rute di sebelah kanan '
        'untuk menghindari Khalid dan para sahabatnya. Beliau sampai di Al-Hudaybiyyah, '
        'menandatangani perjanjian dengan Quraisy bahwa beliau akan melaksanakan Umrah tahun '
        'berikutnya, dan kembali ke Madinah. Khalid menyadari bahwa kaum Quraisy semakin melemah '
        'seiring berlalunya hari. Ia berpikir dalam hatinya, "Apa yang tersisa? Ke mana aku '
        'harus pergi? Ke Raja Najasyi? Tidak bisa, karena bahkan ia pun mengikuti Muhammad, '
        'yang para pengikutnya hidup di bawah perlindungannya. Mungkin aku harus pergi ke '
        'Heraklius? Tidak.</p>'
    ),
}

# ============================================================
# Chapter 065
# ============================================================
translations['065'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Bagaimana aku bisa meninggalkan agamaku Pegang tongkat dari tengahnya untuk Kristen atau '
        'Yahudi, dan hidup di antara orang-orang non-Arab?" Sementara Khalid sedang merenungkan apa '
        'yang harus dilakukan, saat hari dan bulan berlalu hingga genap satu tahun berlalu, datanglah '
        'kesempatan bagi kaum muslimin untuk melaksanakan Umrah. Maka mereka pun menuju Makkah. Nabi '
        'shallallahu \'alaihi wa sallam memasuki Makkah, namun Khalid tidak sanggup menyaksikan kaum '
        'muslimin dalam keadaan ihram. Ia meninggalkan Makkah dan menghilang selama empat hari, yaitu '
        'hari-hari yang Nabi shallallahu \'alaihi wa sallam habiskan di Makkah. Nabi shallallahu '
        '\'alaihi wa sallam melaksanakan Umrahnya dan mulai menatap jalan-jalan dan rumah-rumah '
        'Makkah, untuk mengingat kenangan. Beliau teringat lelaki pemberani itu, Khalid bin '
        'Al-Walid, sehingga beliau berpaling kepada Al-Walid bin Al-Walid, yang adalah saudara '
        'Khalid. Al-Walid adalah seorang muslim yang datang bersama Nabi shallallahu \'alaihi wa '
        'sallam untuk melaksanakan Umrah. Nabi shallallahu \'alaihi wa sallam memutuskan untuk '
        'mengirimkan pesan tidak langsung kepada Khalid, mendorongnya untuk masuk Islam. Nabi '
        'shallallahu \'alaihi wa sallam berkata kepada Al-Walid, "Di mana Khalid?" Al-Walid '
        'terkejut dengan pertanyaan itu. Ia menjawab, "Allah akan membawanya, wahai Rasulullah." '
        'Nabi shallallahu \'alaihi wa sallam lalu berkata, "Seseorang seperti dia tidak bisa bodoh '
        'terhadap Islam! Seandainya ia menyimpan kemampuannya untuk melukai dan bersikap keras '
        'untuk kepentingan kaum muslimin, itu akan lebih baik baginya." Beliau kemudian berkata, '
        '"Jika ia datang kepada kami, kami pasti akan memuliakannya, dan mengutamakannya dari '
        'yang lain." Al-Walid merasa senang dan mulai mencari Khalid di Makkah, namun tidak '
        'menemukannya. Ketika mereka akhirnya memutuskan untuk kembali ke Madinah, ia menulis '
        'surat untuk saudaranya, berkata: Pegang tongkat dari tengahnya "Bismillahirrahmanirrahim. '
        'Amma ba\'du" Aku tidak pernah melihat sesuatu yang lebih mengherankan daripada '
        'ketidaksukaan mu terhadap Islam, mengingat kapasitas intelektualmu! Bisakah ada orang '
        'yang bodoh terhadap sesuatu seperti Islam? Rasulullah shallallahu \'alaihi wa sallam '
        'bertanya kepadaku tentangmu dan berkata, \'Di mana Khalid?\' Aku berkata kepadanya, '
        '\'Allah pasti akan membawanya.\' Nabi shallallahu \'alaihi wa sallam lalu berkata, '
        '\'Seseorang seperti dia tidak bisa bodoh terhadap Islam! Seandainya ia menyimpan '
        'kemampuannya untuk melukai dan bersikap keras untuk kepentingan kaum muslimin, itu '
        'akan lebih baik baginya. Jika ia datang kepada kami, kami pasti akan memuliakannya, '
        'dan mengutamakannya dari yang lain.\' Kejarlah, saudaraku terkasih, semua kesempatan '
        'baik yang telah kamu lewatkan." Khalid berkata, "Ketika surat itu sampai kepadaku, '
        'aku memutuskan untuk pergi. Surat itu meningkatkan ketertarikanku terhadap Islam. '
        'Aku senang bahwa Rasulullah shallallahu \'alaihi wa sallam telah bertanya tentangku. '
        'Aku bermimpi bahwa aku berada di tanah yang sempit dan gersang, yang kemudian aku '
        'tinggalkan menuju tanah yang hijau dan luas. Aku berkata kepada diriku sendiri, '
        '\'Ini pasti mimpi yang benar.\' Ketika aku akhirnya bersiap-siap untuk pergi kepada '
        'Rasulullah shallallahu \'alaihi wa sallam, aku berpikir dalam hati, \'Siapa yang '
        'bisa aku temani dan pergi kepada Rasulullah shallallahu \'alaihi wa sallam?\' Aku '
        'kemudian bertemu Shafwan bin Umayyah dan berkata kepadanya, "Wahai Ibnu Wahb, '
        'tidakkah kamu menyadari situasi kita? Kita seperti gigi geraham yang bertumbukan '
        'satu sama lain. Pegang tongkat dari tengahnya Di sisi lain, Muhammad tampaknya '
        'telah menguasai orang-orang Arab dan non-Arab. Jika kita bergabung dengan Muhammad '
        'dan mengikutinya, maka kehormatannya pasti akan menjadi kehormatan kita?" Namun '
        'Shafwan sangat tidak setuju dan berkata, "Meskipun tidak ada yang tersisa selain '
        'aku, aku tidak akan pernah mengikutinya!" Kami kemudian berpisah. Aku berkata '
        'kepada diriku sendiri, "Pria ini telah terluka. Saudara dan ayahnya terbunuh dalam '
        'Perang Badar." Aku kemudian bertemu \'Ikrimah bin Abi Jahl dan berkata kepadanya '
        'apa yang telah aku katakan kepada Shafwan bin Umayyah, namun ia juga berkata '
        'kepadaku sebagai respons apa yang Shafwan bin Umayyah katakan kepadaku. Aku lalu '
        'berkata kepada diriku sendiri, "Aku akan pergi diam-diam kepada Muhammad tanpa '
        'menyebutnya kepada siapapun." Maka aku pergi ke rumahku, mengambil kendaraanku '
        'dan berangkat, hingga aku bertemu \'Utsman bin Thalhah. Aku berkata kepada diriku, '
        '"Ia adalah temanku. Bagaimana jika aku memberitahunya rencanaku?" Aku lalu '
        'memikirkan pembunuhan kerabatnya dalam peperangan kami melawan kaum muslimin, '
        'sehingga aku tidak ingin mengingatkannya tentang hal itu. Aku kemudian berpikir, '
        '"Tidak apa-apa jika aku memberitahunya, karena aku berangkat sekarang juga!" '
        'Maka aku menyebutkan kepadanya apa yang aku pikir telah terjadi pada Quraisy. '
        'Aku berkata, "Kita seperti rubah yang bersembunyi di dalam liangnya. Jika hanya '
        'sedikit air dituangkan ke dalam liang itu, ia akan keluar." Ia merespons dengan '
        'cepat dan memutuskan untuk pergi bersamaku ke Madinah. Aku berkata kepadanya, '
        '"Aku sebenarnya memutuskan untuk berangkat hari ini ke Madinah. Pegang tongkat '
        'dari tengahnya Inilah tungganganku, sudah siap untukku." Kami kemudian berjanji '
        'untuk bertemu di sebuah tempat yang disebut Ya\'juj.</p>'
    ),
}

# ============================================================
# Chapter 066
# ============================================================
translations['066'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Jika ia tiba lebih dulu, ia akan tinggal di sana dan menungguku. Jika aku tiba lebih '
        'dulu, aku akan tinggal di sana dan menunggunya. Aku kemudian meninggalkan rumahku di '
        'jam-jam terakhir malam, karena takut kaum Quraisy mengetahui keberangkatan kami. Maka '
        'kami bertemu di Ya\'juj sebelum fajar dan berangkat hingga sampai di Al-Hada, dan '
        'mendapati \'Amr bin Al-\'Ash di atas tunggangannya. Ia berkata kepada kami, "Selamat '
        'datang! Ke mana kalian menuju?" Kami berkata, "Dan apa yang membuatmu keluar?" Ia '
        'balik bertanya kepada kami, "Lalu apa yang membuatmu keluar?" "Keinginan kami untuk '
        'masuk Islam dan mengikuti Muhammad," kami menjawab. Ia berkata, "Nah, inilah juga yang '
        'membuatku keluar." Maka kami saling menemani hingga memasuki Madinah. Kami menderumkan '
        'tunggang-tunggangan kami di area berbatu. Rasulullah shallallahu \'alaihi wa sallam '
        'kemudian diberitahu tentang kami. Beliau sangat gembira mendengar berita itu. Aku '
        'kemudian mengenakan pakaian terbaikku dan menuju Rasulullah shallallahu \'alaihi wa '
        'sallam. Di tengah jalan, saudaraku bertemu denganku dan berkata, "Cepatlah! Karena '
        'Rasulullah shallallahu \'alaihi wa sallam telah diberitahu tentangmu dan beliau sangat '
        'bahagia dengan kedatanganmu. Beliau sedang menunggumu." Kami mulai berjalan cepat. '
        'Aku melihat Rasulullah shallallahu \'alaihi wa sallam dan berjalan menuju beliau. '
        'Ketika beliau melihatku dari kejauhan, beliau tersenyum. Beliau terus tersenyum '
        'kepadaku hingga aku akhirnya sampai di hadapannya. Aku lalu Pegang tongkat dari '
        'tengahnya memberi salam kepadanya dan beliau membalas salamku dengan sangat gembira. '
        'Aku berkata, "Aku bersaksi bahwa tidak ada yang berhak disembah selain Allah, dan '
        'bahwa engkau adalah Rasulullah." Beliau berkata, "Segala puji bagi Allah yang telah '
        'memberimu petunjuk. Aku selalu tahu bahwa kamu adalah orang yang cerdas. Aku selalu '
        'berharap kecerdasanmu akan membawamu kepada kebaikanmu sendiri." Aku berkata, '
        '"Wahai Rasulullah, aku tahu bahwa aku pernah ikut serta dalam semua kesusahan yang '
        'harus engkau tanggung, karena aku keras kepala melawan kebenaran. Doakanlah agar '
        'Allah mengampuniku!" Nabi shallallahu \'alaihi wa sallam menjawab, "Islam menghapus '
        'semua yang sebelumnya." Aku berkata, "Wahai Rasulullah, kalau begitu, mohonkanlah '
        'ampunan untukku." Beliau kemudian berdoa untukku, "Ya Allah! Ampunilah Khalid bin '
        'Al-Walid atas semua kesalahannya, dalam menghalangi orang-orang dari jalan Allah!\'" '
        'Setelah itu, Khalid menjadi salah satu pemimpin agama ini. Namun, penerimaannya '
        'terhadap Islam adalah karena pesan tidak langsung yang sampai kepadanya dari '
        'Rasulullah shallallahu \'alaihi wa sallam. Betapa sabar dan bijaksananya beliau! '
        'Mari kita mengadopsi keterampilan-keterampilan ini dalam mempengaruhi orang-orang. '
        'Jika kamu melihat seseorang menjual rokok di tokonya dan ingin memperingatkannya, '
        'pujilah tokonya dan kebersihannya terlebih dahulu, dan doakan agar rezekinya '
        'bertambah. Kemudian peringatkan ia tentang penghasilan yang halal, agar ia '
        'menyadari bahwa kamu tidak memandangnya secara negatif. Sebaliknya, kamu memegang '
        'tongkat dari tengahnya. Pegang tongkat dari tengahnya Bersikaplah cerdas! Carilah '
        'apapun kebaikan yang bisa kamu temukan pada seseorang yang dibandingnya, kejelekan '
        'tampak tidak berarti. Berprasangka baiklah kepada orang lain, hingga mereka '
        'menyadari rasa keadilanmu terhadap mereka dan semakin mencintaimu. Singkatnya... '
        'Ketika orang-orang menyadari bahwa kita memperhatikan tindakan baik mereka sama '
        'seperti kita memperhatikan tindakan buruk mereka, mereka menghargai nasihat kita. '
        'Pegang tongkat dari tengahnya (34) Mudahkanlah perbaikan kesalahan Kesalahan yang '
        'dilakukan orang bermacam-macam. Ada yang besar dan ada yang kecil. Terlepas dari '
        'besarnya kesalahan, semuanya mungkin diperbaiki. Meskipun mungkin tidak mungkin '
        'untuk sepenuhnya memperbaiki konsekuensi buruk dari sebuah kesalahan, namun masih '
        'mungkin untuk memperbaiki banyak hal. Banyak orang gagal memperbaiki kesalahan '
        'mereka karena mereka meragukan kemampuan mereka sendiri untuk memperbaikinya. '
        'Terkadang, cara kita berurusan dengan kesalahan orang lain kebetulan menjadi '
        'bagian dari kesalahan itu sendiri. Misalnya, jika putraku berbuat salah, aku '
        'mungkin menyalahkan dan meremehkannya, dan memperbesar kesalahannya sehingga ia '
        'mungkin mulai berpikir bahwa ia telah jatuh ke dalam sumur yang tidak ada '
        'jalan keluarnya! Maka ia kehilangan harapan akan kemungkinan perbaikan, dan '
        'karenanya tetap dalam kesalahan. Istriku mungkin jatuh ke dalam kesalahan, atau '
        'temanku, dan jika kamu membuatnya menyadari bahwa ia memang telah berbuat salah, '
        'namun ada jalan keluarnya, perbaikan itu mudah, dan kembali kepada kebenaran '
        'lebih baik daripada bertahan dalam kebatilan, hal ini akan terbukti membantu '
        'dalam proses perbaikan. Seorang pria datang kepada Nabi shallallahu \'alaihi wa '
        'sallam untuk memberikan baiat kepadanya atas hijrah. Ia berkata, "Aku datang '
        'untuk memberikan baiat kepadamu atas hijrah, dan aku telah meninggalkan kedua '
        'orang tuaku dalam keadaan menangis." Nabi shallallahu \'alaihi wa sallam tidak '
        'bersikap keras kepadanya, juga tidak meremehkan tindakannya, juga tidak '
        'merendahkan kecerdasannya.</p>'
    ),
}

# ============================================================
# Chapter 067
# ============================================================
translations['067'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Pria itu datang dengan niat baik, dan berpikir bahwa apa yang ia lakukan adalah '
        'yang terbaik. Nabi shallallahu \'alaihi wa sallam membuatnya menyadari bahwa '
        'mudah untuk memperbaiki sebuah kesalahan, sehingga beliau berkata kepadanya '
        'dengan kata-kata sederhana, "Kembalilah kepada mereka dan buatlah mereka tertawa '
        'seperti kamu telah membuat mereka menangis," dan itulah akhir dari masalahnya. '
        'Nabi shallallahu \'alaihi wa sallam akan berurusan dengan orang-orang dengan '
        'cara yang mendorong mereka untuk berbuat baik dan memudahkan mereka, bahkan '
        'jika mereka berbuat salah. Di sini aku menyajikan kepadamu sebuah peristiwa '
        'yang menyakitkan. Meskipun, poin di balik peristiwa ini ada di akhir, aku '
        'tetap ingin menyajikan kisah dari awal untuk manfaat kita. Setiap kali Nabi '
        'shallallahu \'alaihi wa sallam ingin bepergian, beliau mengundi di antara '
        'para istrinya. Siapapun yang menang akan menemaninya dalam perjalanan. Ketika '
        'beliau ingin pergi dalam ekspedisi melawan Banu Al-Mustaliq, beliau mengundi '
        'di antara para istrinya, dan \'A\'isyah yang menang. Maka ia berangkat bersama '
        'Rasulullah shallallahu \'alaihi wa sallam dan ini adalah setelah ayat-ayat '
        'Hijab diturunkan. Ia biasa dibawa dalam sekedup. Setiap kali mereka berhenti, '
        'ia akan meninggalkan sekedup untuk memenuhi kebutuhannya. Setiap kali mereka '
        'ingin berangkat, ia akan kembali ke sekedup. Ketika Nabi shallallahu \'alaihi '
        'wa sallam selesai dengan ekspedisinya, beliau memulai perjalanan kembali ke '
        'Madinah. Ketika beliau tiba lebih dekat ke Madinah, beliau berhenti di suatu '
        'tempat untuk menghabiskan sebagian malam, kemudian memerintahkan para pria '
        'untuk berangkat kembali. Orang-orang kemudian mulai mengumpulkan barang-barang '
        'mereka sebelum berangkat. Sementara itu, \'A\'isyah radhiyallahu \'anha '
        'Mudahkanlah perbaikan kesalahan pergi untuk memenuhi sebagian kebutuhannya. '
        'Ia memakai kalung dengan manik-manik Zafar, sementara memenuhi kebutuhannya, '
        'kalungnya terlepas dari lehernya tanpa ia ketahui. Ketika ia kembali ke unta '
        'dan memutuskan untuk masuk ke sekedup, ia merasakan lehernya namun tidak '
        'menemukan kalungnya, dan orang-orang hampir akan berangkat. Ia segera kembali '
        'ke tempat ia telah memenuhi kebutuhannya dan mulai mencari kalungnya, dan '
        'terlambat. Orang-orang datang dan membawa sekedupnya mengira ia ada di dalamnya, '
        'dan meletakkannya di atas unta. Mereka kemudian menuntun unta itu dan pergi, '
        'begitu pula dengan seluruh pasukan. Adapun \'A\'isyah, setelah pencarian yang '
        'panjang dan melelahkan, ia akhirnya menemukan kalungnya dan kembali ke tempat '
        'pasukan berhenti. \'A\'isyah berkata, "Aku kembali ke tempat itu dan tidak '
        'menemukan siapapun untuk dipanggil atau yang menyahut. Orang-orang telah '
        'pergi. Aku lalu tetap di tempat itu dan berpikir bahwa mungkin orang-orang '
        'akan merindukan aku dan kembali untuk menjemputku. Aku kemudian membungkus '
        'diri dengan jilbabku. Saat aku duduk, aku dikuasai oleh kantuk, sehingga '
        'aku pun tertidur. Demi Allah, aku sedang berbaring ketika Shafwan bin '
        'Al-Mu\'athal melewatiku. Ia juga tertinggal karena beberapa kebutuhannya, '
        'sehingga ia tidak bermalam bersama orang-orang. Ia melihat sebuah sosok '
        'manusia, lalu datang kepadaku dan mengenaliku saat melihatku. Ia pernah '
        'melihatku sebelum hijab diwajibkan bagi kami. Ketika ia melihatku, ia '
        'berkata, \'Inna lillahi wa inna ilaihi raji\'un! Istri Rasulullah '
        'shallallahu \'alaihi wa sallam!\' Aku terbangun karena mendengar kata-kata '
        'yang ia ucapkan saat mengenaliku, sehingga aku menutup wajahku dengan '
        'jilbabku. Demi Allah, ia tidak berbicara Mudahkanlah perbaikan kesalahan '
        'sepatah kata pun kepadaku. Aku tidak mendengar darinya sesuatu pun kecuali '
        'kata-kata yang ia ucapkan pertama kali. Ia datang dan untanya menderum, '
        'menginjak kaki depannya, dan aku pun naik ke atasnya. Ia menuntun unta itu '
        'dari depan dan bergerak untuk mengejar orang-orang. Demi Allah, kami tidak '
        'menyusul orang-orang, juga mereka tidak mengetahui bahwa aku hilang, hingga '
        'kami sampai di pagi hari dan mendapati mereka sedang beristirahat. Sementara '
        'mereka beristirahat, mereka melihat seorang pria yang menuntunku di atas '
        'seekor unta. Saat itu, orang-orang yang suka menfitnah pun berkata apa yang '
        'mereka katakan. Seluruh pasukan terguncang oleh berita itu. Demi Allah, '
        'aku tidak tahu apapun tentang itu semua. Kami kemudian tiba di Madinah dan '
        'aku pun jatuh sakit parah. Tidak ada yang sampai kepadaku dari apa yang '
        'orang-orang katakan. Hal itu memang sampai kepada Rasulullah shallallahu '
        '\'alaihi wa sallam dan kedua orang tuaku, namun mereka tidak pernah '
        'menyebutkannya kepadaku meski sekilas, kecuali bahwa aku memperhatikan '
        'Rasulullah shallallahu \'alaihi wa sallam tidak menunjukkan kelembutannya '
        'kepadaku. Biasanya, setiap kali aku jatuh sakit, beliau menaruh belas '
        'kasihan dan menunjukkan kelembutannya kepadaku. Namun kali ini tidak. '
        'Sebaliknya, jika beliau mengunjungiku sementara aku berada di perawatan '
        'ibuku, beliau hanya berkata, "Bagaimana keadaan wanita itu?" dan tidak '
        'lebih. Aku merasakan hal ini dalam hatiku.</p>'
    ),
}

# ============================================================
# Chapter 068
# ============================================================
translations['068'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Ketika aku melihat bahwa ia menjaga jarak dariku, aku berkata, "Wahai Rasulullah, '
        'apakah engkau mengizinkan aku pergi ke tempat ibuku agar ia bisa merawatku?" Beliau '
        'menjawab, "Tidak masalah." Maka aku pindah ke rumah ibuku, tanpa memiliki pengetahuan '
        'apapun tentang apa yang terjadi. Aku kemudian sembuh dari sakitku setelah lebih dari '
        'dua puluh malam. Suatu malam aku memutuskan untuk keluar memenuhi sebagian kebutuhanku, '
        'bersama Umm Misthah, putri bibi Abu Bakr, dan saat kami berjalan, ia tersandung '
        'jubahnya dan jatuh, atau hampir Mudahkanlah perbaikan kesalahan jatuh. Ia berkata, '
        '\'Celakalah Misthah!\' Aku berkata, \'Alangkah buruknya apa yang kamu katakan! Kamu '
        'mengutuk seorang pria yang menyaksikan Perang Badar!\' Ia berkata, \'Wahai kamu! '
        'Apakah kamu tidak mendengar apa yang ia katakan? Apakah berita itu tidak sampai '
        'kepadamu, wahai putri Abu Bakr?\' \'Berita apa?\' tanyaku. Ia kemudian memberitahuku '
        'apa yang telah dikatakan oleh orang-orang yang suka menfitnah. \'Apakah ini benar-benar '
        'terjadi?\' komentarku. \'Ya, demi Allah, memang terjadi!\' ia menjawab. Demi Allah, '
        'aku tidak mampu memenuhi kebutuhanku sehingga aku kembali dan semakin sakit. Demi '
        'Allah, aku terus menangis hingga aku pikir tangisku akan membelah hatiku. Aku berkata '
        'kepada ibuku, \'Semoga Allah mengampunimu! Orang-orang membicarakan semua ini, dan '
        'kamu tidak menyebutkannya sedikitpun kepadaku.\' Ia menjawab, \'Wahai putriku! '
        'Janganlah khawatir tentang itu. Sangat jarang ada wanita cantik yang menikah dengan '
        'pria yang mencintainya, dan ia memiliki madu-madu lainnya, kecuali mereka semua '
        'mencari-cari kesalahannya, begitu pula orang-orang.\' Aku berkata, \'SubhanAllah! '
        'Apakah orang-orang membicarakan ini?\' Malam itu aku menangis hingga pagi. Airmataku '
        'tidak berhenti, juga aku tidak tidur, hingga pagi tiba sementara aku masih menangis." '
        'Inilah situasi \'A\'isyah. Ia difitnah, sementara ia masih muda dan tidak lebih dari '
        'lima belas tahun. Ia Mudahkanlah perbaikan kesalahan dituduh melakukan zina. Padahal, '
        'ia adalah wanita yang mulia dan suci, istri dari orang paling suci dari semua manusia, '
        'yang tidak pernah menurunkan tirai martabatnya dan tidak pernah mencoreng kehormatannya. '
        'Namun ia berada di sini, menangis di rumah orang tuanya. Adapun Rasulullah shallallahu '
        '\'alaihi wa sallam, beliau juga dipenuhi kesedihan dan kesengsaraan atas \'A\'isyah, '
        'karena Jibril tidak diturunkan, juga Al-Qur\'an tidak diwahyukan untuk memperjelas '
        'masalah ini. Beliau tetap bingung tentang hal ini. Tuduhan-tuduhan yang datang dari '
        'orang-orang munafik terlalu berat untuk ditanggung, begitu pula pembicaraan orang-orang '
        'tentang kehormatan beliau dan istrinya. Ketika kesengsaraan berlangsung lama, Nabi '
        'shallallahu \'alaihi wa sallam berdiri untuk berpidato kepada orang-orang. Beliau '
        'memuji dan mengagungkan Allah, kemudian berkata, "Wahai manusia! Ada apa dengan '
        'sebagian orang yang menyakitiku berkenaan dengan keluargaku? Mereka berbicara dusta '
        'tentang keluargaku. Demi Allah, aku tidak mengetahui mereka kecuali kebaikan. Mereka '
        'juga membicarakan hal serupa tentang seorang pria, dan demi Allah, aku tidak '
        'mengetahuinya kecuali kebaikan. Ia tidak pernah memasuki rumah-rumahku kecuali ia '
        'bersamaku." Ketika Nabi shallallahu \'alaihi wa sallam berkata demikian, pemimpin '
        'suku Al-Aws, Sa\'d bin Mu\'adz berdiri dan berkata, "Wahai Rasulullah, jika mereka '
        'dari Al-Aws, kami akan mencegah mereka dari menyakitimu. Dan jika mereka dari saudara '
        'kami, Al-Khazraj, maka perintahkan kami, karena mereka layak mendapatkan leher-leher '
        'mereka ditebas!" Ketika pemimpin suku Al-Khazraj, Sa\'d bin \'Ubadah mendengar ini, '
        'ia berdiri. Meskipun ia adalah orang yang shalih, ia diliputi semangat kabilah. Ia '
        'berdiri dan berkata, "Demi Allah, kamu berdusta! Leher-leher mereka tidak akan '
        'ditebas! Demi Allah, kamu hanya mengatakan ini karena mengetahui mereka dari '
        'Al-Khazraj. Jika mereka dari kabilahmu, kamu tidak akan mengatakan ini!" Usaid bin '
        'Hudhair berkata mendengar ini, "Demi Allah, kamu berdusta! Demi Allah, kami akan '
        'membunuhnya! Tapi kamu adalah orang munafik, berargumen untuk membela orang-orang '
        'munafik!" Orang-orang kemudian saling melompat ke arah satu sama lain dan hampir '
        'terjadi pertempuran, sementara Rasulullah shallallahu \'alaihi wa sallam masih '
        'berdiri di mimbarnya. Beliau terus menenangkan mereka hingga akhirnya mereka diam. '
        'Nabi shallallahu \'alaihi wa sallam, setelah menyaksikan ini, turun dari mimbar '
        'dan masuk ke dalam rumahnya. Ketika beliau menyadari bahwa situasi tidak bisa '
        'diredakan dengan berpidato kepada publik, beliau berpaling kepada keluarganya, '
        'dan orang-orang yang paling istimewa baginya, untuk mencari solusi. Maka beliau '
        'memanggil \'Ali dan Usamah bin Zaid untuk meminta saran mereka. Usamah memuji '
        '\'A\'isyah dan berkata, "Wahai Rasulullah! Kami tidak mengetahui tentang keluargamu '
        'kecuali kebaikan. Semua ini adalah kebohongan dan kepalsuan." \'Ali berkata, '
        '"Wahai Rasulullah, banyak wanita yang bisa engkau nikahi. Engkau selalu bisa '
        'menggantikannya.</p>'
    ),
}

# ============================================================
# Chapter 069
# ============================================================
translations['069'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Namun, tanyakanlah kepada budak wanita itu, karena ia akan berkata jujur." Rasulullah '
        'shallallahu \'alaihi wa sallam kemudian memanggil Bareerah dan bertanya, "Wahai Bareerah! '
        'Apakah kamu memperhatikan sesuatu yang mencurigakan tentang \'A\'isyah?" "Tidak pernah! '
        'Demi yang mengutusmu sebagai Nabi!" jawab Bareerah, "Demi Allah, aku tidak mengetahui '
        'dirinya kecuali kebaikan. Aku tidak pernah memperhatikan apapun yang salah pada \'A\'isyah, '
        'kecuali bahwa ia adalah gadis muda. Aku membuat adonan roti dan memintanya untuk '
        'menjaganya, namun ia malah tertidur dan membiarkan adonan itu dimakan oleh kambing-kambing '
        'peliharaan." Mudahkanlah perbaikan kesalahan Bagaimana mungkin budak wanita itu curiga '
        'terhadap \'A\'isyah, karena ia adalah wanita muda yang shalih yang dibesarkan oleh orang '
        'paling jujur di umat ini, yaitu Abu Bakr, dan menikah dengan orang terbaik dari seluruh '
        'manusia? Bahkan, bagaimana ia bisa dicurigai, sementara ia adalah orang yang paling '
        'dicintai oleh Rasulullah shallallahu \'alaihi wa sallam? Tentu saja Rasulullah '
        'shallallahu \'alaihi wa sallam tidak akan mencintai kecuali yang baik. Maka ia '
        'benar-benar tidak bersalah, namun Allah memutuskan untuk mengujinya agar meningkatkan '
        'pahalanya dan meninggikan kemuliaannya. Banyak hari berlalu, sementara rasa sakit '
        '\'A\'isyah terus meningkat, karena ia berbaring gelisah dan terbaring sakit dan tidak '
        'berselera makan atau minum. Nabi shallallahu \'alaihi wa sallam mencoba memecahkan '
        'masalah dengan berpidato kepada orang-orang, namun hampir berubah menjadi peperangan. '
        'Beliau mencoba memecahkan masalah di rumah dengan bertanya kepada \'Ali dan Zaid, '
        'namun tidak menemukan solusi. Pada tahap ini, beliau ingin mengakhirinya bersama '
        '\'A\'isyah. Ia berkata, "Hari itu aku menangis tanpa henti dan tidak bisa tidur. '
        'Aku terus menangis selama dua hari berikutnya dan tidak bisa tidur. Kedua orang '
        'tuaku berpikir bahwa tangisku yang terus-menerus akan membelah hatiku." Nabi '
        'shallallahu \'alaihi wa sallam kemudian menuju rumah Abu Bakr. Beliau meminta '
        'izinnya dan mengunjungi \'A\'isyah sementara ia bersama kedua orang tuanya dan '
        'seorang wanita dari kaum Anshar. Ini adalah pertama kalinya Nabi shallallahu '
        '\'alaihi wa sallam memasuki rumah Abu Bakr sejak orang-orang mulai menyebarkan '
        'rumor. Beliau tidak melihat \'A\'isyah selama sebulan, karena beliau telah '
        'menunggu sebulan dan tidak ada sesuatu yang diwahyukan tentang \'A\'isyah. '
        'Nabi shallallahu \'alaihi wa sallam masuk kepada \'A\'isyah dan mendapatinya '
        'terbaring, Mudahkanlah perbaikan kesalahan seolah-olah seperti anak burung yang '
        'dicabut bulunya, karena tangisnya yang terus-menerus dan penderitaannya. Ia '
        'menangis, begitu pula wanita yang ada di sebelahnya, tidak bisa menahan diri, '
        'Nabi shallallahu \'alaihi wa sallam duduk, memuji dan mengagungkan Allah, lalu '
        'berkata, "Amma ba\'du, wahai \'A\'isyah, hal seperti ini dan itu telah sampai '
        'kepadaku tentangmu," Nabi shallallahu \'alaihi wa sallam kemudian menyebutkan '
        'fitnah itu, dan apapun yang telah dikatakan tentangnya terkait kesalahan besar. '
        'Beliau kemudian ingin menjelaskan kepadanya bahwa tidak peduli kesalahan apa yang '
        'dilakukan seseorang, tidak sulit untuk memperbaikinya. Beliau berkata kepadanya, '
        '"Jika kamu tidak bersalah, maka Allah Yang Maha Agung akan menyatakan kesucianmu. '
        'Namun jika kamu telah melakukan dosa, maka mintalah ampunan Allah dan bertaubatlah '
        'kepada-Nya. Karena ketika seorang hamba Allah mengakui dosanya dan bertaubat, '
        'Allah menerima taubatnya." Maka beliau menyajikan cara keluar yang mudah dari '
        'kesalahan, jika itu benar-benar terjadi, tanpa mempersulit lebih lanjut atau '
        'memperpanjang masalah. \'A\'isyah berkata, "Ketika Nabi shallallahu \'alaihi wa '
        'sallam selesai berbicara, airmataku berhenti dan aku menunggu kedua orang tuaku '
        'untuk merespons Rasulullah shallallahu \'alaihi wa sallam atas namaku, namun '
        'mereka tidak merespons. Aku berkata kepada ayahku, \'Tolong responlah Rasulullah '
        'shallallahu \'alaihi wa sallam tentang apa yang ia katakan.\' Ia menjawab, '
        '\'Demi Allah, aku tidak tahu apa yang harus aku katakan kepada Rasulullah!\' '
        'Aku lalu berkata kepada ibuku, \'Tolong responlah Rasulullah shallallahu \'alaihi '
        'wa sallam atas namaku!\' Ia berkata, \'Demi Allah, aku tidak tahu apa yang harus '
        'aku katakan kepada Rasulullah!\' Mudahkanlah perbaikan kesalahan Demi Allah! '
        'Aku tidak mengetahui ada keluarga yang lebih menderita daripada keluarga Abu '
        'Bakr saat itu. Ketika aku menyadari bahwa keduanya tidak mampu mengucapkan '
        'sepatah kata pun atas namaku, aku semakin menangis. Aku lalu berkata, \'Tidak '
        'pernah! Demi Allah, aku tidak akan pernah bertaubat kepada Allah atas apa yang '
        'kamu sebutkan! Demi Allah, aku sekarang tahu bahwa kamu telah mendengar rumor itu, '
        'ia telah menetap di hatimu dan kamu mempercayainya. Jika aku katakan kepadamu '
        'bahwa aku tidak bersalah – dan Allah Yang Maha Agung dan Mulia mengetahui bahwa '
        'aku tidak bersalah – kamu tidak akan pernah mempercayaiku! Namun jika aku mengakui '
        'sesuatu – meskipun Allah mengetahui bahwa aku tidak bersalah – kamu akan '
        'mempercayaiku! Demi Allah, aku tidak menemukan untuk kamu dan diriku sendiri '
        'contoh lain kecuali seperti kata ayah Yusuf ketika ia berkata, \'Maka kesabaran '
        'yang baik itulah kesabaranku, dan Allah-lah yang dimohon pertolongan-Nya terhadap '
        'apa yang kamu ceritakan!\'" Ia berkata, "Aku kemudian berpaling dan berbaring di '
        'tempat tidurku.</p>'
    ),
}

# ============================================================
# Chapter 070
# ============================================================
translations['070'] = {
    'title_id': '5. Maukah Anda Bertemu Dengannya di Luar Institusi? (Lanjutan)',
    'content_id': (
        '<p>Demi Allah, aku tahu bahwa aku tidak bersalah dan bahwa Allah juga akan menyatakan '
        'kesucianku. Namun, demi Allah, aku tidak bisa membayangkan bahwa wahyu akan diturunkan '
        'tentang aku, yang akan dibacakan selamanya. Aku tidak layak bahwa Allah berbicara '
        'tentang musibahku dalam sebuah bacaan. Aku hanya berharap bahwa Rasulullah shallallahu '
        '\'alaihi wa sallam akan bermimpi di mana Allah Yang Maha Agung akan menyatakan '
        'kesucianku. Namun, demi Allah, Rasulullah shallallahu \'alaihi wa sallam tidak beranjak '
        'dari tempat duduknya, dan tidak ada seorangpun yang meninggalkan rumah, kecuali beliau '
        'diliputi oleh keadaan yang sering menimpanya ketika menerima wahyu. Allah sedang '
        'mewahyukan kepada Nabi-Nya. Adapun aku, ketika aku melihat beliau menerima wahyu, '
        'demi Allah aku tidak menjadi takut atau khawatir, karena aku tahu bahwa aku tidak '
        'bersalah, dan Mudahkanlah perbaikan kesalahan bahwa Allah tidak akan menzalimiku. '
        'Adapun kedua orang tuaku, maka demi Yang memegang jiwa \'A\'isyah di tangan-Nya, '
        'ketika Rasulullah shallallahu \'alaihi wa sallam pulih, aku pikir jiwa mereka '
        'akan pergi sewaktu-waktu karena takut bahwa Allah mengonfirmasi apa yang dikatakan '
        'orang-orang. Namun, ketika Nabi shallallahu \'alaihi wa sallam pulih, beliau '
        'tertawa dan mulai mengusap keringat dari wajahnya. Hal pertama yang beliau katakan '
        'adalah, \'Kabar gembira, wahai \'A\'isyah! Allah telah menyatakan kesucianmu!\' '
        'Aku berkata, \'Alhamdulillah!\' Allah telah mewahyukan, \'Sesungguhnya orang-orang '
        'yang membawa berita bohong itu adalah dari golongan kamu juga. Janganlah kamu kira '
        'bahwa berita bohong itu buruk bagi kamu bahkan ia adalah baik bagi kamu. Tiap-tiap '
        'seseorang dari mereka mendapat balasan dari dosa yang dikerjakannya. Dan siapa di '
        'antara mereka yang mengambil bagian yang terbesar dalam penyiaran berita bohong itu '
        'baginya azab yang besar. Mengapa di waktu kamu mendengar berita bohong itu '
        'orang-orang mukminin dan mukminat tidak bersangka baik terhadap diri mereka sendiri, '
        'dan mengapa tidak berkata: Ini adalah suatu berita bohong yang nyata? Mengapa mereka '
        '(yang menuduh itu) tidak mendatangkan empat orang saksi atas berita bohong itu? Oleh '
        'karena mereka tidak mendatangkan saksi-saksi, maka mereka itulah pada sisi Allah '
        'orang-orang yang dusta.\' Allah lebih lanjut mengancam mereka dengan firman-Nya, '
        '\'Sesungguhnya orang-orang yang ingin agar (berita) perbuatan yang amat keji itu '
        'tersiar di kalangan orang-orang yang beriman, bagi mereka azab yang pedih di dunia '
        'dan di akhirat. Dan Allah mengetahui, sedang kamu tidak mengetahui.\'" Rasulullah '
        'shallallahu \'alaihi wa sallam kemudian keluar menemui orang-orang dan berpidato '
        'kepada mereka dengan membacakan apa yang Allah wahyukan kepadanya dari Al-Qur\'an '
        'tentang urusan ini. Beliau kemudian menghukum mereka yang bersalah atas fitnah. '
        'Mudahkanlah perbaikan kesalahan Maka, sangat penting bagi kamu untuk berurusan '
        'dengan orang yang berbuat salah seolah-olah ia adalah pasien yang membutuhkan '
        'pengobatan, bukan berlebihan dalam mengutuk dan bersikap keras kepadanya. Ini '
        'karena orang yang berbuat salah mungkin sampai pada titik di mana ia mulai '
        'berpikir bahwa kamu sebenarnya senang dengan kesalahannya. Seorang dokter yang '
        'peduli adalah seseorang yang peduli terhadap kesehatan pasien lebih dari mereka '
        'peduli terhadapnya sendiri. Nabi shallallahu \'alaihi wa sallam bersabda, '
        '"Perumpamaanku dan kalian ibarat seorang pria yang menyalakan api. Belalang dan '
        'kupu-kupu mulai jatuh ke dalam api dan pria itu terus melindungi mereka dari api. '
        'Aku menahan kalian dari jatuh ke dalam api dan kalian melepaskan diri dari '
        'tanganku." Sebuah pendapat... Terkadang, cara kita memperbaiki sebuah kesalahan '
        'kebetulan menjadi kesalahan yang lebih besar dari kesalahan itu sendiri. '
        'Mudahkanlah perbaikan kesalahan (35) Pendapat lain Sebagaimana orang-orang berbeda '
        'dalam sifat dan fisik, mereka juga berbeda dalam pandangan, keyakinan, dan cara '
        'bergaul. Jika kamu pernah merasa bahwa seseorang telah berbuat salah, maka '
        'nasihatinya dan cobalah memperbaiki kesalahannya, namun jika ia tidak mendengarkan, '
        'jangan kemudian menganggapnya sebagai salah satu musuhmu. Hadapilah situasi dengan '
        'optimis, sesuai dengan kemampuanmu sendiri. Jika kamu mencoba memperbaiki kesalahan '
        'salah satu temanmu, dan ia menolak nasihatmu, jangan jadikan persahabatan menjadi '
        'permusuhan. Teruslah bersikap baik kepadanya, dengan harapan bahwa setidaknya '
        'kesalahannya tidak bertambah. Dikatakan, "Kasihanilah! Karena beberapa bentuk '
        'kejahatan lebih bisa ditanggung daripada yang lain." Jika kamu bergaul dengan '
        'orang-orang dengan ceria, kamu tidak akan marah atas setiap kesalahan kecil '
        'atau besar mereka dan hidup bahagia selamanya. \'A\'isyah radhiyallahu \'anha '
        'berkata, "Rasulullah shallallahu \'alaihi wa sallam tidak pernah mencari balas '
        'dendam untuk dirinya sendiri. Beliau tidak pernah memukul siapapun dengan '
        'tangannya, baik wanita maupun pembantu, kecuali saat berperang di jalan Allah. '
        'Beliau tidak pernah disakiti berkenaan dengan pribadinya hingga beliau pernah '
        'mencari balas dendam dari orang yang menyakitinya, kecuali jika salah satu '
        'kehormatan Allah dilanggar, dalam hal itu Allah yang akan membalasnya." (Muslim) '
        'Maka tidak diragukan lagi Nabi shallallahu \'alaihi wa sallam pernah marah, '
        'namun kemarahannya adalah karena Allah. Beliau tidak pernah marah untuk '
        'kepentingan dirinya sendiri.</p>'
    ),
}


# Write all chapters
written = []
skipped = []
for ch_num, trans in translations.items():
    fpath = BOOK_DIR / f'{ch_num}.json'
    data = json.loads(fpath.read_text())

    if data.get('content_id', '').strip():
        print(f'Chapter {ch_num}: SKIPPED (already has content_id)')
        skipped.append(ch_num)
        continue

    data['content_id'] = trans['content_id']
    if not data.get('title_id', '').strip():
        data['title_id'] = trans['title_id']

    fpath.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
    print(f'Chapter {ch_num}: DONE')
    written.append(ch_num)

print(f'\nBatch 3 (056-070) complete.')
print(f'Written: {len(written)} chapters: {written}')
print(f'Skipped: {len(skipped)} chapters: {skipped}')
