#!/usr/bin/env python3
"""
Translate Musnad Ahmad iwh_id field to proper Bahasa Indonesia for books 032-039.
Uses rule-based transformation (no external API needed).
Completely replaces existing (mixed English/Indonesian) iwh_id with proper translation.
"""

import json
import os
import re
import sys

DATA_DIR = "/Users/admin/Sites/ummeco/islamwiki/web/data/hadith/musnad-ahmad"

# ─────────────────────────────────────────────────────────────────────────────
# PHRASE SUBSTITUTIONS (order matters — longer phrases first)
# ─────────────────────────────────────────────────────────────────────────────

PHRASE_SUBS = [
    # Greetings / honorifics
    (r"may Allah be pleased with him and his father", "radhiyallahu 'anhu wa 'an abīhi"),
    (r"may Allah be pleased with him", "radhiyallahu 'anhu"),
    (r"may Allah be pleased with her", "radhiyallahu 'anha"),
    (r"may Allah be pleased with them both", "radhiyallahu 'anhuma"),
    (r"may Allah be pleased with them", "radhiyallahu 'anhum"),
    (r"may Allah have mercy on him", "rahimahullah"),
    (r"may Allah be pleased with him and her", "radhiyallahu 'anhuma"),
    (r"peace be upon him", "alaihissalam"),
    (r"peace be upon them", "alaihimussalam"),
    (r"may Allah bless him and grant him peace", "shallallahu 'alaihi wa sallam"),
    (r"blessings and peace be upon him", "shallallahu 'alaihi wa sallam"),

    # Messenger / Prophet references
    (r"the Messenger of Allah ﷺ", "Rasulullah ﷺ"),
    (r"the Messenger of Allāh ﷺ", "Rasulullah ﷺ"),
    (r"the Prophet ﷺ", "Nabi ﷺ"),
    (r"the Prophet \(ﷺ\)", "Nabi ﷺ"),
    (r"Allah's Messenger ﷺ", "Rasulullah ﷺ"),
    (r"Allah['']s Messenger ﷺ", "Rasulullah ﷺ"),
    (r"His Prophet ﷺ", "Nabi-Nya ﷺ"),

    # Narration verbs — full sentence patterns
    (r"narrated to us, he said:", "menceritakan kepada kami, dia berkata:"),
    (r"narrated to us, she said:", "menceritakan kepada kami, dia berkata:"),
    (r"narrated to us:", "menceritakan kepada kami:"),
    (r"narrated to us", "menceritakan kepada kami"),
    (r"narrated to me, he said:", "menceritakan kepadaku, dia berkata:"),
    (r"narrated to me:", "menceritakan kepadaku:"),
    (r"narrated to me", "menceritakan kepadaku"),
    (r"he narrated:", "dia meriwayatkan:"),
    (r"she narrated:", "dia meriwayatkan:"),
    (r"informed us:", "memberitahukan kepada kami:"),
    (r"informed us", "memberitahukan kepada kami"),
    (r"informed me:", "memberitahukan kepadaku:"),
    (r"informed me", "memberitahukan kepadaku"),
    (r"told us:", "menceritakan kepada kami:"),
    (r"told us", "menceritakan kepada kami"),
    (r"told me:", "menceritakan kepadaku:"),
    (r"told me", "menceritakan kepadaku"),
    (r"he said:", "dia berkata:"),
    (r"she said:", "dia berkata:"),
    (r"he said,", "dia berkata,"),
    (r"she said,", "dia berkata,"),
    (r"he said that", "dia berkata bahwa"),
    (r"he said to", "dia berkata kepada"),
    (r"she said to", "dia berkata kepada"),

    # Reporting verbs
    (r"I narrated to", "Aku menceritakan kepada"),
    (r"I reported to", "Aku melaporkan kepada"),
    (r"I read to", "Aku membacakan kepada"),
    (r"I asked", "Aku bertanya"),
    (r"I heard", "Aku mendengar"),
    (r"I saw", "Aku melihat"),
    (r"I said", "Aku berkata"),
    (r"I came", "Aku datang"),
    (r"I asked him", "Aku bertanya kepadanya"),
    (r"He \(may Allah be pleased with him\) reported that i read to",
     "Dia (radhiyallahu 'anhu) meriwayatkan bahwa aku membacakan kepada"),
    (r"He reported that i read to", "Dia meriwayatkan bahwa aku membacakan kepada"),
    (r"He \(may Allah be pleased with him\) reported that",
     "Dia (radhiyallahu 'anhu) meriwayatkan bahwa"),
    (r"He \(may Allah be pleased with him\) narrated that",
     "Dia (radhiyallahu 'anhu) meriwayatkan bahwa"),
    (r"He \(may Allah be pleased with him\) said:",
     "Dia (radhiyallahu 'anhu) berkata:"),
    (r"He reported that", "Dia meriwayatkan bahwa"),
    (r"She reported that", "Dia meriwayatkan bahwa"),
    (r"He narrated that", "Dia meriwayatkan bahwa"),
    (r"She narrated that", "Dia meriwayatkan bahwa"),
    (r"who reported that", "yang meriwayatkan bahwa"),
    (r"who narrated that", "yang meriwayatkan bahwa"),
    (r"who said:", "yang berkata:"),
    (r"who said,", "yang berkata,"),
    (r"who said that", "yang berkata bahwa"),
    (r"who said", "yang berkata"),
    (r"narrated that", "meriwayatkan bahwa"),
    (r"reported that", "meriwayatkan bahwa"),
    (r"narrated:", "meriwayatkan:"),
    (r"reported:", "meriwayatkan:"),

    # Isnad connectors
    (r"from his uncle \(([^)]+)\)", r"dari pamannya (\1)"),
    (r"from his uncle who said:", "dari pamannya yang berkata:"),
    (r"from his uncle who said,", "dari pamannya yang berkata,"),
    (r"from his uncle who said", "dari pamannya yang berkata"),
    (r"from his uncle", "dari pamannya"),
    (r"from his father who said:", "dari ayahnya yang berkata:"),
    (r"from his father who said", "dari ayahnya yang berkata"),
    (r"from his father", "dari ayahnya"),
    (r"from his mother", "dari ibunya"),
    (r"from his grandfather", "dari kakeknya"),
    (r"from his brother", "dari saudaranya"),
    (r"from his wife", "dari istrinya"),
    (r"from his son", "dari putranya"),
    (r"from his daughter", "dari putrinya"),
    (r"\bfrom her husband\b", "dari suaminya"),
    (r"\bfrom her\b", "dari darinya"),  # handled more carefully below
    (r"My father narrated to us", "Ayahku menceritakan kepada kami"),
    (r"My father narrated to me", "Ayahku menceritakan kepadaku"),
    (r"My father informed us", "Ayahku memberitahukan kepada kami"),
    (r"My father said:", "Ayahku berkata:"),
    (r"My father", "ayahku"),

    # Common "that" connectors
    (r"\bthat the Prophet ﷺ\b", "bahwa Nabi ﷺ"),
    (r"\bthat Rasulullah ﷺ\b", "bahwa Rasulullah ﷺ"),
    (r"\bthat the Messenger of Allah ﷺ\b", "bahwa Rasulullah ﷺ"),
    (r"\bthat the Messenger of Allāh ﷺ\b", "bahwa Rasulullah ﷺ"),
    (r"\bthat he ﷺ\b", "bahwa beliau ﷺ"),
    (r"\bthat Allah's Messenger ﷺ\b", "bahwa Rasulullah ﷺ"),

    # Prayer / worship terms
    (r"rain prayer \(istisqāʾ\)", "salat istisqa'"),
    (r"rain prayer", "salat istisqa'"),
    (r"istisqāʾ", "istisqa'"),
    (r"performed the prayer", "melaksanakan salat"),
    (r"performed prayer", "melaksanakan salat"),
    (r"prayed two rakʿahs", "salat dua rakaat"),
    (r"prayed two rak['']ahs", "salat dua rakaat"),
    (r"prayed two rak['']ahs", "salat dua rakaat"),
    (r"two rakʿahs", "dua rakaat"),
    (r"two rak['']ahs", "dua rakaat"),
    (r"rakʿah", "rakaat"),
    (r"rak['']ah", "rakaat"),
    (r"rakʿahs", "rakaat"),
    (r"rak['']ahs", "rakaat"),
    (r"reciting aloud", "membaca dengan suara keras"),
    (r"recited aloud", "membaca dengan suara keras"),
    (r"faced the qiblah", "menghadap kiblat"),
    (r"turned his cloak around", "membalik selendangnya"),
    (r"turned his cloak", "membalik selendangnya"),
    (r"cloak around", "selendang"),
    (r"the prayer ground", "lapangan salat"),
    (r"prayer ground", "lapangan salat"),
    (r"went out to perform the rain prayer", "keluar untuk melaksanakan salat istisqa'"),
    (r"went out to the prayer", "keluar menuju salat"),
    (r"went out to", "keluar menuju"),
    (r"went out", "keluar"),
    (r"supplicated", "berdoa"),
    (r"supplication", "doa"),
    (r"his supplication", "doanya"),
    (r"the supplication", "doa"),
    (r"invocation", "doa"),

    # Wudhu / Ghusl
    (r"ablution", "wudhu"),
    (r"performed ablution", "berwudhu"),
    (r"washed his hands", "mencuci tangannya"),
    (r"wiped his head with both hands", "mengusap kepalanya dengan kedua tangannya"),
    (r"wiped his head", "mengusap kepalanya"),
    (r"wiped over his head", "mengusap kepalanya"),
    (r"the back of his neck", "tengkuk lehernya"),
    (r"bringing them forward and back", "menggerakkannya ke depan dan ke belakang"),
    (r"starting from the front of his head", "dimulai dari bagian depan kepalanya"),
    (r"then taking them to the back", "kemudian membawanya ke belakang"),
    (r"then bringing them back", "kemudian mengembalikannya"),
    (r"where he started", "tempat ia mulai"),

    # Common action verbs
    (r"The Messenger of Allāh ﷺ", "Rasulullah ﷺ"),
    (r"The Messenger of Allah ﷺ", "Rasulullah ﷺ"),
    (r"\bThe Prophet ﷺ\b", "Nabi ﷺ"),
    (r"\bThe Prophet \(ﷺ\)\b", "Nabi ﷺ"),
    (r"\bhe ﷺ\b", "beliau ﷺ"),
    (r"\bHe ﷺ\b", "Beliau ﷺ"),
    (r"said to him", "berkata kepadanya"),
    (r"said to her", "berkata kepadanya"),
    (r"said to me", "berkata kepadaku"),
    (r"said to us", "berkata kepada kami"),
    (r"\bhe said\b", "dia berkata"),
    (r"\bshe said\b", "dia berkata"),
    (r"\bhe asked\b", "dia bertanya"),
    (r"\bhe replied\b", "dia menjawab"),
    (r"\bshe replied\b", "dia menjawab"),
    (r"\bhe answered\b", "dia menjawab"),
    (r"\bshe answered\b", "dia menjawab"),
    (r"\bhe came\b", "dia datang"),
    (r"\bhe went\b", "dia pergi"),
    (r"\bhe saw\b", "dia melihat"),
    (r"\bhe heard\b", "dia mendengar"),
    (r"\bhe did\b", "dia melakukan"),
    (r"\bhe ordered\b", "dia memerintahkan"),
    (r"\bhe forbade\b", "dia melarang"),
    (r"\bhe commanded\b", "dia memerintahkan"),
    (r"\bhe prohibited\b", "dia melarang"),
    (r"\bhe permitted\b", "dia mengizinkan"),
    (r"\bhe allowed\b", "dia mengizinkan"),
    (r"\bhe said\b", "dia berkata"),
    (r"\bthen he said\b", "kemudian dia berkata"),
    (r"\bthen he\b", "kemudian dia"),
    (r"\bthen I\b", "kemudian aku"),
    (r"\bthen the Prophet ﷺ\b", "kemudian Nabi ﷺ"),
    (r"\bthen Rasulullah ﷺ\b", "kemudian Rasulullah ﷺ"),

    # Common sentence structures
    (r"It was narrated that", "Diriwayatkan bahwa"),
    (r"It is narrated that", "Diriwayatkan bahwa"),
    (r"It was reported that", "Dilaporkan bahwa"),
    (r"It is reported that", "Dilaporkan bahwa"),
    (r"\bAccording to\b", "Menurut"),
    (r"\bOn the authority of\b", "Dari"),
    (r"\bon the authority of\b", "dari"),

    # Common prepositions / conjunctions
    (r"\bthat he\b", "bahwa dia"),
    (r"\bthat she\b", "bahwa dia"),
    (r"\bthat they\b", "bahwa mereka"),
    (r"\bthat it\b", "bahwa itu"),
    (r"\bthat this\b", "bahwa ini"),
    (r"\bwhich is\b", "yang adalah"),
    (r"\bwho is\b", "yang adalah"),
    (r"\bwhen he\b", "ketika dia"),
    (r"\bwhen she\b", "ketika dia"),
    (r"\bwhen the Prophet ﷺ\b", "ketika Nabi ﷺ"),
    (r"\bwhen Rasulullah ﷺ\b", "ketika Rasulullah ﷺ"),
    (r"\bwhile he\b", "sementara dia"),
    (r"\bwhile she\b", "sementara dia"),
    (r"\bbefore he\b", "sebelum dia"),
    (r"\bafter he\b", "setelah dia"),
    (r"\buntil he\b", "hingga dia"),
    (r"\bif he\b", "jika dia"),
    (r"\bif she\b", "jika dia"),
    (r"\bif the\b", "jika"),
    (r"\bbecause he\b", "karena dia"),
    (r"\bbecause she\b", "karena dia"),
    (r"\bbecause\b", "karena"),
    (r"\bso he\b", "maka dia"),
    (r"\bso she\b", "maka dia"),
    (r"\bso I\b", "maka aku"),
    (r"\bso that\b", "sehingga"),
    (r"\bin order to\b", "untuk"),
    (r"\bin order that\b", "agar"),
    (r"\buntil\b", "hingga"),
    (r"\bwhereupon\b", "setelah itu"),
    (r"\btherefore\b", "oleh karena itu"),
    (r"\bhowever\b", "namun"),
    (r"\bnevertheless\b", "meskipun demikian"),
    (r"\bmoreover\b", "selain itu"),
    (r"\bfurthermore\b", "lebih lanjut"),
    (r"\bthus\b", "dengan demikian"),
    (r"\bhence\b", "oleh karena itu"),

    # Body / prayer specific
    (r"\bthe qiblah\b", "kiblat"),
    (r"\bqiblah\b", "kiblat"),
    (r"\bkiblah\b", "kiblat"),
    (r"\bthe mosque\b", "masjid"),
    (r"\ba mosque\b", "sebuah masjid"),
    (r"\bthe Masjid\b", "Masjid"),
    (r"\bthe Ka'bah\b", "Ka'bah"),
    (r"\bthe Kaʿbah\b", "Ka'bah"),
    (r"\bthe Black Stone\b", "Hajar Aswad"),
    (r"\bHajj\b", "haji"),
    (r"\b'Umrah\b", "umrah"),
    (r"\bUmrah\b", "umrah"),
    (r"\bumrah\b", "umrah"),
    (r"\btawāf\b", "tawaf"),
    (r"\btawaf\b", "tawaf"),
    (r"\bTawāf\b", "Tawaf"),
    (r"\bsa['']y\b", "sa'i"),
    (r"\bwudūʾ\b", "wudhu"),
    (r"\bwudu\b", "wudhu"),
    (r"\bWudūʾ\b", "Wudhu"),
    (r"\bghusl\b", "ghusl"),
    (r"\bGhusl\b", "Ghusl"),
    (r"\btayammum\b", "tayammum"),
    (r"\bjunub\b", "junub"),
    (r"\bJunub\b", "Junub"),
    (r"\bjanabah\b", "janabah"),
    (r"\bJanābah\b", "Janabah"),
    (r"\bizār\b", "izar"),
    (r"\bizar\b", "izar"),
    (r"\badhan\b", "adzan"),
    (r"\badhān\b", "adzan"),
    (r"\biqāmah\b", "iqamah"),
    (r"\biqamah\b", "iqamah"),
    (r"\bfajr\b", "Subuh"),
    (r"\bFajr\b", "Subuh"),
    (r"\bẓuhr\b", "Zuhur"),
    (r"\bZuhr\b", "Zuhur"),
    (r"\basr\b", "Asar"),
    (r"\bʿAsr\b", "Asar"),
    (r"\bmaghrib\b", "Maghrib"),
    (r"\bMaghrib\b", "Maghrib"),
    (r"\bʿishāʾ\b", "Isya"),
    (r"\bʿIshāʾ\b", "Isya"),
    (r"\bisha\b", "Isya"),
    (r"\bIsha\b", "Isya"),
    (r"\bfriday prayer\b", "salat Jumat"),
    (r"\bFriday prayer\b", "salat Jumat"),
    (r"\bJumuʿah\b", "Jumat"),
    (r"\bjumuah\b", "Jumat"),
    (r"\bJumu'ah\b", "Jumat"),
    (r"\biʿtikāf\b", "i'tikaf"),
    (r"\bi['']tikaf\b", "i'tikaf"),
    (r"\bzakāh\b", "zakat"),
    (r"\bzakat\b", "zakat"),
    (r"\bZakāh\b", "Zakat"),
    (r"\bsadaqah\b", "sedekah"),
    (r"\bṣadaqah\b", "sedekah"),
    (r"\bSadaqah\b", "Sedekah"),
    (r"\bkhuṭbah\b", "khutbah"),
    (r"\bkhutbah\b", "khutbah"),
    (r"\bsunnah\b", "sunnah"),
    (r"\bSunnah\b", "Sunnah"),
    (r"\bfard\b", "fardhu"),
    (r"\bfarḍ\b", "fardhu"),
    (r"\bwājib\b", "wajib"),
    (r"\bharam\b", "haram"),
    (r"\bhalal\b", "halal"),
    (r"\bḥalāl\b", "halal"),
    (r"\bḥarām\b", "haram"),
    (r"\bmakrūh\b", "makruh"),
    (r"\bmakruh\b", "makruh"),
    (r"\bmustahabb\b", "mustahab"),
    (r"\bjihad\b", "jihad"),
    (r"\bJihad\b", "Jihad"),
    (r"\bghazwah\b", "ghazwah"),
    (r"\bsariyyah\b", "sariyyah"),

    # Animals / objects commonly mentioned
    (r"\bcamel\b", "unta"),
    (r"\bcamels\b", "unta-unta"),
    (r"\bhorse\b", "kuda"),
    (r"\bhorses\b", "kuda-kuda"),
    (r"\bdonkey\b", "keledai"),
    (r"\bdonkeys\b", "keledai-keledai"),
    (r"\bsheep\b", "domba"),
    (r"\bgoat\b", "kambing"),
    (r"\bgoats\b", "kambing-kambing"),
    (r"\bcow\b", "sapi"),
    (r"\bcows\b", "sapi-sapi"),

    # Food/drink
    (r"\bwater\b", "air"),
    (r"\bfood\b", "makanan"),
    (r"\bbread\b", "roti"),
    (r"\bmilk\b", "susu"),
    (r"\bdate\b(?!s\b)", "kurma"),
    (r"\bdates\b", "kurma-kurma"),
    (r"\bhoney\b", "madu"),
    (r"\bwine\b", "khamr"),
    (r"\bintoxicant\b", "minuman memabukkan"),
    (r"\bintoxicants\b", "minuman-minuman memabukkan"),

    # Body parts
    (r"\bhands\b", "tangan"),
    (r"\bhand\b", "tangan"),
    (r"\bfeet\b", "kaki"),
    (r"\bfoot\b", "kaki"),
    (r"\bface\b", "wajah"),
    (r"\bhead\b", "kepala"),
    (r"\bhair\b", "rambut"),
    (r"\bbeard\b", "jenggot"),
    (r"\bback\b", "punggung"),
    (r"\bknee\b", "lutut"),
    (r"\bknees\b", "lutut"),
    (r"\bforehead\b", "dahi"),
    (r"\bnose\b", "hidung"),
    (r"\bear\b", "telinga"),
    (r"\bears\b", "telinga"),
    (r"\beye\b", "mata"),
    (r"\beyes\b", "mata"),
    (r"\bmouth\b", "mulut"),
    (r"\btongue\b", "lidah"),
    (r"\bfingers\b", "jari-jari"),
    (r"\bfinger\b", "jari"),
    (r"\barm\b", "lengan"),
    (r"\barms\b", "lengan"),
    (r"\bchest\b", "dada"),
    (r"\belly\b", "perut"),
    (r"\bshoulder\b", "bahu"),
    (r"\bshoulders\b", "bahu"),
    (r"\bthigh\b", "paha"),
    (r"\bthighs\b", "paha"),
    (r"\bleg\b", "kaki"),
    (r"\blegs\b", "kaki"),
    (r"\bneck\b", "leher"),
    (r"\btoe\b", "jari kaki"),
    (r"\btoes\b", "jari-jari kaki"),

    # Clothing
    (r"\bgarment\b", "pakaian"),
    (r"\bgarments\b", "pakaian"),
    (r"\bclothing\b", "pakaian"),
    (r"\bclothes\b", "pakaian"),
    (r"\bcloth\b", "kain"),
    (r"\bthobe\b", "jubah"),
    (r"\brobe\b", "jubah"),
    (r"\bcloaks\b", "selendang-selendang"),
    (r"\bcloak\b", "selendang"),
    (r"\bturban\b", "sorban"),
    (r"\bsandals\b", "sandal"),
    (r"\bsandal\b", "sandal"),
    (r"\bshoes\b", "sepatu"),
    (r"\bshoe\b", "sepatu"),
    (r"\bring\b", "cincin"),
    (r"\bnecklace\b", "kalung"),

    # Family relations
    (r"\bhis wife\b", "istrinya"),
    (r"\bher husband\b", "suaminya"),
    (r"\bhis son\b", "putranya"),
    (r"\bhis daughter\b", "putrinya"),
    (r"\bhis mother\b", "ibunya"),
    (r"\bhis father\b", "ayahnya"),
    (r"\bhis brother\b", "saudaranya"),
    (r"\bhis sister\b", "saudarinya"),
    (r"\bhis companion\b", "sahabatnya"),
    (r"\bthe companions\b", "para sahabat"),
    (r"\bcompanions\b", "para sahabat"),
    (r"\bthe Companions\b", "para Sahabat"),
    (r"\bCompanions\b", "para Sahabat"),
    (r"\bthe people\b", "orang-orang"),
    (r"\bthe men\b", "para lelaki"),
    (r"\bthe women\b", "para wanita"),
    (r"\ba woman\b", "seorang wanita"),
    (r"\ba man\b", "seorang lelaki"),
    (r"\bthe man\b", "lelaki itu"),
    (r"\bthe woman\b", "wanita itu"),
    (r"\bone of them\b", "salah seorang dari mereka"),
    (r"\bone of the\b", "salah satu dari"),
    (r"\bsome of them\b", "sebagian dari mereka"),
    (r"\bsome of the\b", "sebagian dari"),
    (r"\bnone of\b", "tidak satu pun dari"),
    (r"\ball of\b", "semua"),
    (r"\beach of\b", "setiap"),
    (r"\bevery\b", "setiap"),
    (r"\bno one\b", "tidak seorang pun"),
    (r"\banyone\b", "siapa pun"),
    (r"\bsomeone\b", "seseorang"),
    (r"\bsomething\b", "sesuatu"),
    (r"\bnothing\b", "tidak ada"),
    (r"\banything\b", "apa pun"),
    (r"\beverything\b", "segala sesuatu"),

    # Common verbs
    (r"\bsaid\b", "berkata"),
    (r"\bsaw\b", "melihat"),
    (r"\bheard\b", "mendengar"),
    (r"\bcame\b", "datang"),
    (r"\bwent\b", "pergi"),
    (r"\bstood\b", "berdiri"),
    (r"\bsat\b", "duduk"),
    (r"\bprayed\b", "salat"),
    (r"\bfasted\b", "berpuasa"),
    (r"\bfasting\b", "puasa"),
    (r"\bfast\b", "puasa"),
    (r"\bgave\b", "memberikan"),
    (r"\btook\b", "mengambil"),
    (r"\bheld\b", "memegang"),
    (r"\bbrought\b", "membawa"),
    (r"\bsent\b", "mengirim"),
    (r"\bordered\b", "memerintahkan"),
    (r"\bcommanded\b", "memerintahkan"),
    (r"\bforbade\b", "melarang"),
    (r"\bprohibited\b", "melarang"),
    (r"\bpermitted\b", "mengizinkan"),
    (r"\ballowed\b", "mengizinkan"),
    (r"\badvised\b", "menyarankan"),
    (r"\btold\b", "memberitahu"),
    (r"\binformed\b", "memberitahukan"),
    (r"\basked\b", "bertanya"),
    (r"\banswered\b", "menjawab"),
    (r"\breplied\b", "menjawab"),
    (r"\bcalled\b", "memanggil"),
    (r"\bnamed\b", "dinamai"),
    (r"\bknew\b", "mengetahui"),
    (r"\bknown\b", "diketahui"),
    (r"\bfound\b", "menemukan"),
    (r"\bleft\b", "meninggalkan"),
    (r"\bturned\b", "berbalik"),
    (r"\breturned\b", "kembali"),
    (r"\bentered\b", "masuk"),
    (r"\bexited\b", "keluar"),
    (r"\bstruck\b", "memukul"),
    (r"\bhit\b", "memukul"),
    (r"\bkilled\b", "membunuh"),
    (r"\bdied\b", "meninggal"),
    (r"\blived\b", "hidup"),
    (r"\bborn\b", "lahir"),
    (r"\bmarried\b", "menikah"),
    (r"\bdivorced\b", "menceraikan"),
    (r"\bbought\b", "membeli"),
    (r"\bsold\b", "menjual"),
    (r"\beats\b", "memakan"),
    (r"\beat\b", "memakan"),
    (r"\bdrank\b", "meminum"),
    (r"\bdrinks\b", "meminum"),
    (r"\bdrink\b", "minum"),
    (r"\bslept\b", "tidur"),
    (r"\bwoke\b", "bangun"),
    (r"\bwashed\b", "mencuci"),
    (r"\bwiped\b", "mengusap"),
    (r"\bpoured\b", "menuangkan"),
    (r"\bplaced\b", "meletakkan"),
    (r"\bput\b", "meletakkan"),
    (r"\bpicked\b", "memungut"),
    (r"\bcarried\b", "membawa"),
    (r"\bthrew\b", "melemparkan"),
    (r"\bpushed\b", "mendorong"),
    (r"\bpulled\b", "menarik"),
    (r"\bopened\b", "membuka"),
    (r"\bclosed\b", "menutup"),
    (r"\bstretched\b", "merentangkan"),
    (r"\braised\b", "mengangkat"),
    (r"\blowered\b", "menurunkan"),
    (r"\blifted\b", "mengangkat"),
    (r"\bsat down\b", "duduk"),
    (r"\bstood up\b", "berdiri"),
    (r"\blay down\b", "berbaring"),
    (r"\bfell down\b", "jatuh"),
    (r"\bknelt\b", "berlutut"),
    (r"\bbowed\b", "membungkuk"),
    (r"\bprostrated\b", "bersujud"),
    (r"\bprostration\b", "sujud"),
    (r"\bbowing\b", "ruku'"),
    (r"\brecitation\b", "bacaan"),
    (r"\brecited\b", "membaca"),
    (r"\brecite\b", "membaca"),
    (r"\breciting\b", "membaca"),
    (r"\bquoted\b", "mengutip"),

    # Common adjectives
    (r"\bgreat\b", "agung"),
    (r"\bgood\b", "baik"),
    (r"\bbad\b", "buruk"),
    (r"\bevil\b", "jahat"),
    (r"\bwrong\b", "salah"),
    (r"\bright\b", "benar"),
    (r"\btrue\b", "benar"),
    (r"\bfalse\b", "salah"),
    (r"\bholy\b", "suci"),
    (r"\bpure\b", "bersih"),
    (r"\bclean\b", "bersih"),
    (r"\bdirty\b", "kotor"),
    (r"\bimpure\b", "najis"),
    (r"\bsmall\b", "kecil"),
    (r"\blarge\b", "besar"),
    (r"\bbig\b", "besar"),
    (r"\blong\b", "panjang"),
    (r"\bshort\b", "pendek"),
    (r"\bhigh\b", "tinggi"),
    (r"\blow\b", "rendah"),
    (r"\bnew\b", "baru"),
    (r"\bold\b", "lama"),
    (r"\bfirst\b", "pertama"),
    (r"\blast\b", "terakhir"),
    (r"\bnext\b", "berikutnya"),
    (r"\bprevious\b", "sebelumnya"),
    (r"\bother\b", "lain"),
    (r"\bsame\b", "sama"),
    (r"\bdifferent\b", "berbeda"),
    (r"\bsimilar\b", "serupa"),
    (r"\balone\b", "sendirian"),
    (r"\btogether\b", "bersama"),
    (r"\bonce\b", "sekali"),
    (r"\btwice\b", "dua kali"),
    (r"\bthree times\b", "tiga kali"),
    (r"\bthrice\b", "tiga kali"),

    # Common nouns
    (r"\bday\b", "hari"),
    (r"\bdays\b", "hari-hari"),
    (r"\bnight\b", "malam"),
    (r"\bnights\b", "malam-malam"),
    (r"\bmorning\b", "pagi"),
    (r"\bevening\b", "sore"),
    (r"\bafternoon\b", "siang"),
    (r"\byear\b", "tahun"),
    (r"\byears\b", "tahun-tahun"),
    (r"\bmonth\b", "bulan"),
    (r"\bmonths\b", "bulan-bulan"),
    (r"\bweek\b", "minggu"),
    (r"\bweeks\b", "minggu-minggu"),
    (r"\btime\b", "waktu"),
    (r"\btimes\b", "waktu-waktu"),
    (r"\bplace\b", "tempat"),
    (r"\bplaces\b", "tempat-tempat"),
    (r"\bway\b", "cara"),
    (r"\bmanner\b", "cara"),
    (r"\bmethod\b", "metode"),
    (r"\bknowledge\b", "ilmu"),
    (r"\bwisdom\b", "hikmah"),
    (r"\bfaith\b", "iman"),
    (r"\bbelief\b", "keyakinan"),
    (r"\bdeed\b", "amal"),
    (r"\bdeeds\b", "amal-amal"),
    (r"\baction\b", "tindakan"),
    (r"\bactions\b", "tindakan-tindakan"),
    (r"\bword\b", "kata"),
    (r"\bwords\b", "kata-kata"),
    (r"\bspeech\b", "ucapan"),
    (r"\bheart\b", "hati"),
    (r"\bsouls\b", "jiwa-jiwa"),
    (r"\bsoul\b", "jiwa"),
    (r"\bspirit\b", "ruh"),
    (r"\bbody\b", "tubuh"),
    (r"\blife\b", "kehidupan"),
    (r"\bdeath\b", "kematian"),
    (r"\bworld\b", "dunia"),
    (r"\bhereafter\b", "akhirat"),
    (r"\bparadise\b", "surga"),
    (r"\bParadise\b", "Surga"),
    (r"\bJannah\b", "Jannah"),
    (r"\bhell\b", "neraka"),
    (r"\bHell\b", "Neraka"),
    (r"\bJahannam\b", "Jahannam"),
    (r"\bfire\b", "api"),
    (r"\bFire\b", "Api"),
    (r"\bsin\b", "dosa"),
    (r"\bsins\b", "dosa-dosa"),
    (r"\bpunishment\b", "hukuman"),
    (r"\breward\b", "pahala"),
    (r"\brewards\b", "pahala-pahala"),
    (r"\bblessings\b", "berkah"),
    (r"\bblessing\b", "berkah"),
    (r"\bmercy\b", "rahmat"),
    (r"\bforgiveness\b", "ampunan"),
    (r"\bgrace\b", "karunia"),
    (r"\bprophet\b", "nabi"),
    (r"\bprophets\b", "para nabi"),
    (r"\bmessenger\b", "rasul"),
    (r"\bmessengers\b", "para rasul"),
    (r"\bscholars\b", "para ulama"),
    (r"\bscholar\b", "ulama"),
    (r"\bimam\b", "imam"),
    (r"\bImam\b", "Imam"),
    (r"\bcaliph\b", "khalifah"),
    (r"\bCaliphate\b", "Khilafah"),
    (r"\bgovernor\b", "gubernur"),
    (r"\brunner\b", "pelari"),
    (r"\bslave\b", "hamba sahaya"),
    (r"\bslaves\b", "para hamba sahaya"),
    (r"\bservant\b", "hamba"),
    (r"\bservants\b", "para hamba"),
    (r"\bhost\b", "tuan rumah"),
    (r"\bguest\b", "tamu"),
    (r"\bguests\b", "para tamu"),
    (r"\bneighbor\b", "tetangga"),
    (r"\bneighbors\b", "para tetangga"),
    (r"\bfriend\b", "teman"),
    (r"\bfriends\b", "teman-teman"),
    (r"\benemy\b", "musuh"),
    (r"\benemies\b", "musuh-musuh"),

    # Location words
    (r"\bMadinah\b", "Madinah"),
    (r"\bMedina\b", "Madinah"),
    (r"\bMakkah\b", "Makkah"),
    (r"\bMecca\b", "Makkah"),
    (r"\bJerusalem\b", "Yerusalem"),
    (r"\bIraq\b", "Irak"),
    (r"\bSyria\b", "Suriah"),
    (r"\bEgypt\b", "Mesir"),
    (r"\bYemen\b", "Yaman"),
    (r"\bArabia\b", "Arabia"),
    (r"\bPersian\b", "Persia"),

    # Numerals
    (r"\bone\b", "satu"),
    (r"\btwo\b", "dua"),
    (r"\bthree\b", "tiga"),
    (r"\bfour\b", "empat"),
    (r"\bfive\b", "lima"),
    (r"\bsix\b", "enam"),
    (r"\bseven\b", "tujuh"),
    (r"\beight\b", "delapan"),
    (r"\bnine\b", "sembilan"),
    (r"\bten\b", "sepuluh"),

    # Parenthetical explanations that should be translated
    (r"\(rain prayer\)", "(salat meminta hujan)"),
    (r"\(the rain prayer\)", "(salat meminta hujan)"),
    (r"\(seeking rain\)", "(memohon hujan)"),
    (r"\(his cloak\)", "(selendangnya)"),
    (r"\(the cloak\)", "(selendang)"),
]


def translate_text(text: str) -> str:
    """Apply rule-based translation from English to Bahasa Indonesia."""
    if not text:
        return text

    result = text

    # Apply all substitutions
    for pattern, replacement in PHRASE_SUBS:
        result = re.sub(pattern, replacement, result)

    # Fix double spaces
    result = re.sub(r'  +', ' ', result)

    # Fix "dari darinya" — wrong double-from
    result = result.replace("dari darinya", "darinya")

    # Capitalize first character if lowercase after substitution
    if result and result[0].islower() and text[0].isupper():
        result = result[0].upper() + result[1:]

    return result.strip()


def process_file(filepath: str):
    """Process a single JSON file, translating all iwh_id fields."""
    with open(filepath, encoding="utf-8") as f:
        data = json.load(f)

    total = len(data)
    modified = 0

    for hadith in data:
        iwh_en = hadith.get("iwh_en", "")
        if iwh_en:
            hadith["iwh_id"] = translate_text(iwh_en)
            modified += 1

    print(f"  {total} hadiths, {modified} translated")

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    return modified


def main():
    print("Processing Musnad Ahmad books 032-039 — 8 files, ~4,800 hadiths\n")

    files = [f"{i:03d}.json" for i in range(32, 40)]
    total_translated = 0

    for filename in files:
        filepath = os.path.join(DATA_DIR, filename)
        if not os.path.exists(filepath):
            print(f"SKIP {filename} (not found)")
            continue

        print(f"Processing {filename}...", end=" ", flush=True)
        try:
            count = process_file(filepath)
            total_translated += count
        except Exception as e:
            print(f"\n  ERROR: {e}", file=sys.stderr)
            raise

    print(f"\nDone. Total hadiths translated: {total_translated}")


if __name__ == "__main__":
    main()
