#!/usr/bin/env python3
"""
Islam.wiki Books — Source Directory Initializer
=================================================
Creates source/ subdirectory in all canonical book directories.
Also identifies books with zero chapter files and logs them.

Usage:
  python scripts/books/init-source-dirs.py
  python scripts/books/init-source-dirs.py --dry-run
  python scripts/books/init-source-dirs.py --empty-only
"""

import argparse
import json
import os
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent / "web"
BOOKS_DIR = REPO_ROOT / "data" / "books"
CLASSICAL_JSON = BOOKS_DIR / "classical.json"
OUTPUT_FILE = Path(__file__).parent / "empty-books-list.json"


def count_chapter_files(book_dir: Path) -> int:
    """Count chapter JSON files in a book directory."""
    if not book_dir.exists():
        return -1
    return len([
        f for f in book_dir.iterdir()
        if f.suffix == ".json"
        and f.name not in ("meta.json", "index.json")
    ])


def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize source/ directories for all books")
    parser.add_argument("--dry-run", action="store_true", help="Don't create directories")
    parser.add_argument("--empty-only", action="store_true", help="Only report empty books, don't create source/")
    args = parser.parse_args()

    books = json.loads(CLASSICAL_JSON.read_text("utf-8"))
    canonical = [b for b in books if b.get("canonical") is not False]

    print(f"Processing {len(canonical)} canonical books…\n")

    source_dirs_created = 0
    source_dirs_existing = 0
    empty_books: list[dict] = []
    missing_dirs: list[str] = []

    for book in canonical:
        slug = book["slug"]
        book_dir = BOOKS_DIR / slug
        source_dir = book_dir / "source"

        chapter_count = count_chapter_files(book_dir)

        if chapter_count == -1:
            missing_dirs.append(slug)
            print(f"  ❌ MISSING DIR: {slug}")
            continue

        if chapter_count == 0:
            empty_books.append({
                "slug": slug,
                "title_en": book.get("title_en"),
                "author_name_en": book.get("author_name_en"),
                "subject": book.get("subject"),
                "language_original": book.get("language_original"),
                "volumes": book.get("volumes"),
                "source_url_primary": book.get("source_url_primary"),
                "source_status": book.get("source_status"),
                "is_short_treatise": book.get("is_short_treatise"),
                "has_no_chapters": book.get("has_no_chapters"),
                "chapter_zero_only": book.get("chapter_zero_only"),
            })
            print(f"  📭 EMPTY: {slug} (0 chapter files)")

        if not args.empty_only:
            if source_dir.exists():
                source_dirs_existing += 1
            else:
                if not args.dry_run:
                    source_dir.mkdir(exist_ok=True)
                    # Write a README for the source directory
                    readme = source_dir / "README.md"
                    readme.write_text(
                        f"# Source files for {book.get('title_en', slug)}\n\n"
                        f"Place raw source files here before processing:\n"
                        f"- `source-en.md` — extracted English text\n"
                        f"- `source-ar.md` — extracted Arabic text\n"
                        f"- `source-id.md` — extracted Indonesian text\n"
                        f"- `raw.*` — original downloaded files (PDF, HTML, etc.)\n\n"
                        f"Generated by `scripts/books/init-source-dirs.py`\n",
                        encoding="utf-8"
                    )
                    source_dirs_created += 1
                else:
                    print(f"  (dry-run) Would create: {source_dir}")
                    source_dirs_created += 1

    # Save empty books list
    if not args.dry_run and not args.empty_only:
        OUTPUT_FILE.write_text(
            json.dumps(empty_books, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8"
        )
        print(f"\nEmpty books list saved: {OUTPUT_FILE}")

    # Summary
    print(f"\n{'='*60}")
    print(f"Canonical books:        {len(canonical)}")
    if not args.empty_only:
        print(f"source/ dirs created:   {source_dirs_created}")
        print(f"source/ dirs existing:  {source_dirs_existing}")
    print(f"Empty books (0 chapters): {len(empty_books)}")
    print(f"Missing book dirs:        {len(missing_dirs)}")

    if missing_dirs:
        print(f"\nMissing directories (need mkdir):")
        for s in missing_dirs:
            print(f"  {s}")

    if empty_books:
        print(f"\nEmpty books requiring content:")
        for b in empty_books:
            url_status = "✓ has URL" if b.get("source_url_primary") else "✗ no URL"
            print(f"  {b['slug']} ({b.get('subject','?')}) — {url_status}")

    if not args.dry_run and empty_books:
        print(f"\nFull list written to: {OUTPUT_FILE}")

    print(f"{'='*60}")


if __name__ == "__main__":
    main()
